// backup: download + folder via File System Access API, handle kept in IndexedDB
function backupPayload(){return{app:'Varga Gestionale',version:2,createdAt:new Date().toISOString(),data:db}}function downloadBackup(){let blob=new Blob([JSON.stringify(backupPayload(),null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`Varga-Gestionale-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href);db.meta.lastBackup=new Date().toLocaleString('it-IT');S.set('vg_meta',db.meta);refresh()}$('exportBackup').onclick=downloadBackup;$('importBackup').onchange=async e=>{let f=e.target.files?.[0];if(!f)return;try{let o=JSON.parse(await f.text());if(!o.data)throw Error();Object.assign(db,o.data);save();companyToForm();clearQuote();alert('Backup ripristinato.')}catch{alert('Backup non valido.')}};
let folderHandle=null;function idb(){return new Promise((res,rej)=>{let r=indexedDB.open('varga-gestionale',1);r.onupgradeneeded=()=>r.result.createObjectStore('kv');r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}async function setHandle(h){let d=await idb();return new Promise((res,rej)=>{let t=d.transaction('kv','readwrite');t.objectStore('kv').put(h,'backupFolder');t.oncomplete=res;t.onerror=()=>rej(t.error)})}async function getHandle(){let d=await idb();return new Promise((res,rej)=>{let r=d.transaction('kv').objectStore('kv').get('backupFolder');r.onsuccess=()=>res(r.result||null);r.onerror=()=>rej(r.error)})}async function writeFolder(silent=false){if(!folderHandle)folderHandle=await getHandle();if(!folderHandle){if(!silent)alert('Scegli prima una cartella.');return}try{let perm=await folderHandle.queryPermission({mode:'readwrite'});if(perm!=='granted'&&!silent)perm=await folderHandle.requestPermission({mode:'readwrite'});if(perm!=='granted')return;let fh=await folderHandle.getFileHandle('Varga-Gestionale-backup.json',{create:true}),w=await fh.createWritable();await w.write(JSON.stringify(backupPayload(),null,2));await w.close();db.meta.lastBackup=new Date().toLocaleString('it-IT');db.meta.backupFolder=folderHandle.name;S.set('vg_meta',db.meta);if(!silent){refresh();alert('Backup completato nella cartella scelta.')}}catch(err){console.warn(err);if(!silent)alert('Non riesco a scrivere nella cartella selezionata.')}}async function autoFolderBackup(){try{if(folderHandle||await getHandle())writeFolder(true)}catch{}}$('chooseFolder').onclick=async()=>{if(!window.showDirectoryPicker)return alert('Questa funzione richiede Chrome o Edge su Windows.');try{folderHandle=await showDirectoryPicker({mode:'readwrite'});await setHandle(folderHandle);db.meta.backupFolder=folderHandle.name;S.set('vg_meta',db.meta);refresh()}catch{}};$('backupNow').onclick=()=>writeFolder(false);function updateBackupInfo(){$('lastBackup').textContent=db.meta.lastBackup||'Mai';$('backupDest').textContent=db.meta.backupFolder||'Non collegata';$('folderInfo').textContent=db.meta.backupFolder?`Cartella collegata: ${db.meta.backupFolder}`:'Nessuna cartella collegata.';$('recordCount').textContent=['clients','quotes','jobs','invoices','expenses','deadlines','documents','entries','cantieriRows','consuntivi','vcCommesse','vcImpianti','vcSquadre','vcOre','vcSegnalazioni','vcUtenti','vcRecords'].reduce((s,k)=>s+db[k].length,0)}
// Cloud multiutente: Firestore conserva uno snapshot del gestionale; Drive resta archivio file.
const DEFAULT_FIREBASE_CONFIG={apiKey:'AIzaSyBHZG9D1H5YOT9QUzG-cdSdftlreDJNa_k',authDomain:'hera-app-6cd2b.firebaseapp.com',projectId:'hera-app-6cd2b',storageBucket:'hera-app-6cd2b.firebasestorage.app',messagingSenderId:'645390631375',appId:'1:645390631375:web:df3659a23812560e4012ba'};
const cloudCfg=S.get('vg_cloudConfig',{});if(!cloudCfg.firebaseConfig){cloudCfg.firebaseConfig=DEFAULT_FIREBASE_CONFIG;cloudCfg.workspaceId=cloudCfg.workspaceId||'varga-azienda';S.set('vg_cloudConfig',cloudCfg);}let cloudApp=null,cloudAuth=null,cloudStore=null,cloudFunctions=null,cloudUser=null,cloudUnsub=null,cloudPushTimer=null,applyingRemote=false,pendingLoginNotice='';
function cloudDisplayName(){return $('displayName')?.value.trim()||cloudCfg.displayName||cloudUser?.email||'Operatore'}
function cloudStatus(text){if($('cloudStatus'))$('cloudStatus').textContent=text;if($('cloudUser'))$('cloudUser').textContent=cloudUser?.email||'Non connesso';if($('cloudWorkspaceLabel'))$('cloudWorkspaceLabel').textContent=($('workspaceId')?.value||cloudCfg.workspaceId||'-')}
function cloudState(){return{priceLists:db.priceLists,entries:db.entries,clients:db.clients,quotes:db.quotes,jobs:db.jobs,invoices:db.invoices,expenses:db.expenses,deadlines:db.deadlines,documents:db.documents,consuntivi:db.consuntivi,depurazioneConsuntivi:db.depurazioneConsuntivi,company:db.company}}
function loadCloudFields(){if(cloudCfg.firebaseConfig)$('firebaseConfig').value=JSON.stringify(cloudCfg.firebaseConfig,null,2);$('workspaceId').value=cloudCfg.workspaceId||'varga-azienda';$('displayName').value=cloudCfg.displayName||'';cloudStatus(cloudCfg.firebaseConfig?'Configurato':'Non configurato')}
function parseFirebaseConfig(){try{return JSON.parse($('firebaseConfig').value.trim())}catch{return null}}
function loginMessage(text='',error=false){const el=$('loginMessage');if(!el)return;el.textContent=text;el.hidden=!text;el.classList.toggle('error',Boolean(error))}
function setLoginBusy(busy,label='Accesso in corso…'){const loading=$('loginLoading'),form=$('loginForm');if(loading){loading.hidden=!busy;const strong=loading.querySelector('strong');if(strong)strong.textContent=label}if(form)form.hidden=busy;['loginEmailButton','loginGoogleButton','createLoginAccount'].forEach(id=>{if($(id))$(id).disabled=busy})}
function showLogin(message='',error=false){document.body.classList.remove('auth-loading','auth-ready');document.body.classList.add('auth-locked');document.querySelector('.app-shell')?.setAttribute('aria-hidden','true');setLoginBusy(false);loginMessage(message,error);setTimeout(()=>$('loginEmail')?.focus(),0)}
function unlockApp(user){document.body.classList.remove('auth-loading','auth-locked');document.body.classList.add('auth-ready');document.querySelector('.app-shell')?.setAttribute('aria-hidden','false');loginMessage();const name=user?.displayName||user?.email?.split('@')[0]||'Utente',role={admin:'Amministratore',ufficio:'Ufficio',operatore:'Operatore'}[window.cloudUserRole]||'Utente autorizzato';if($('sidebarUserName'))$('sidebarUserName').textContent=name;if($('sidebarUserRole'))$('sidebarUserRole').textContent=role;if($('sidebarAvatar'))$('sidebarAvatar').textContent=name.trim().charAt(0).toUpperCase()||'V'}
function friendlyAuthError(error){const code=String(error?.code||'');if(code.includes('invalid-credential')||code.includes('wrong-password')||code.includes('user-not-found'))return'Email o password non corrette.';if(code.includes('invalid-email'))return'Inserisci un indirizzo email valido.';if(code.includes('too-many-requests'))return'Troppi tentativi. Attendi qualche minuto e riprova.';if(code.includes('popup-closed'))return'Accesso Google annullato.';if(code.includes('popup-blocked'))return'Il browser ha bloccato la finestra Google. Consenti i popup e riprova.';if(code.includes('email-already-in-use'))return'Esiste già un account con questa email: usa la stessa password di Varga Cantieri.';if(code.includes('weak-password'))return error?.message||'La password deve contenere almeno 10 caratteri.';return error?.message||'Accesso non riuscito. Riprova.'}
async function prepareAuthPersistence(){if(!cloudAuth)return;const keep=$('loginRemember')?.checked!==false;await cloudAuth.setPersistence(keep?firebase.auth.Auth.Persistence.LOCAL:firebase.auth.Auth.Persistence.SESSION)}
async function loginWithEmail(email,password){if(!cloudAuth&&!initCloud())throw new Error('Servizio di accesso non disponibile.');await prepareAuthPersistence();return cloudAuth.signInWithEmailAndPassword(email,password)}
async function loginWithGoogle(){if(!cloudAuth&&!initCloud())throw new Error('Servizio di accesso non disponibile.');await prepareAuthPersistence();const provider=new firebase.auth.GoogleAuthProvider();provider.setCustomParameters({prompt:'select_account'});return cloudAuth.signInWithPopup(provider)}
function initCloud(){let cfg=cloudCfg.firebaseConfig||DEFAULT_FIREBASE_CONFIG;if(!cfg||typeof firebase==='undefined'){cloudStatus('Firebase non caricato');showLogin('Servizio di accesso non disponibile. Ricarica la pagina.',true);return false}try{cloudApp=firebase.apps.find(a=>a.name==='vargaGestionale')||firebase.initializeApp(cfg,'vargaGestionale');cloudAuth=cloudApp.auth();cloudStore=cloudApp.firestore();cloudFunctions=typeof cloudApp.functions==='function'?cloudApp.functions('europe-west1'):null;cloudAuth.onAuthStateChanged(async u=>{cloudUser=u||null;cloudStatus(u?'Verifica accesso…':'Configurato');if(!u){stopCloudRealtime();if(window.cloudUserSignedOut)cloudUserSignedOut();const notice=pendingLoginNotice;pendingLoginNotice='';showLogin(notice,false);return}setLoginBusy(true,'Verifica autorizzazione Varga Cantieri…');try{if(typeof window.authorizeCloudUser!=='function')throw Error('Controllo autorizzazioni non disponibile.');const allowed=await window.authorizeCloudUser(u);if(allowed){cloudStatus('Connesso');startCloudRealtime();unlockApp(u)}else{stopCloudRealtime();cloudStatus('Non autorizzato');showLogin(window.cloudUserAccessReason||`L'account ${u.email||''} non è autorizzato in Varga Cantieri.`,true)}}catch(e){console.warn(e);stopCloudRealtime();cloudStatus('Errore autorizzazione');showLogin('Non riesco a verificare la tua autorizzazione in Varga Cantieri. Controlla la connessione e riprova.',true)}});return true}catch(e){console.warn(e);cloudStatus('Errore configurazione');showLogin('Configurazione di accesso non disponibile.',true);return false}}
window.VargaCloud=Object.freeze({
  async authToken(){if(!cloudUser)throw Error('Accedi al Gestionale per continuare.');return cloudUser.getIdToken()},
  async createTreeWorkOrder(payload){if(!cloudStore||!cloudUser)throw Error('Connessione cloud non disponibile.');const commessa=cloudStore.collection('commesse').doc('potature-abbattimenti'),impianto=commessa.collection('impianti').doc(payload.id);const batch=cloudStore.batch();batch.set(commessa,{nome:'Potature Abbattimenti',codice:'POT-ABB',speciale:true,tipoSpeciale:'POTATURE_ABBATTIMENTI',catastoAlberi:true,attiva:true,updatedAt:new Date()},{merge:true});batch.set(impianto,{...payload,id:impianto.id,commessaId:'potature-abbattimenti',stato:'da_fare',done:false,updatedByUid:cloudUser.uid,updatedAt:new Date()},{merge:true});await batch.commit();return impianto.id}
});
function workspaceRef(){let id=($('workspaceId').value||cloudCfg.workspaceId||'varga-azienda').trim();return cloudStore.collection('vargaGestionaleWorkspaces').doc(id)}
function stopCloudRealtime(){if(cloudUnsub){cloudUnsub();cloudUnsub=null}}
function startCloudRealtime(){if(!cloudStore||!cloudUser)return;stopCloudRealtime();cloudUnsub=workspaceRef().onSnapshot(snap=>{if(!snap.exists)return;let o=snap.data();if(o.updatedBy===cloudUser.uid)return;try{let remote=JSON.parse(o.snapshotJson||'{}');applyingRemote=true;Object.keys(cloudState()).forEach(k=>{if(remote[k]!==undefined)db[k]=remote[k]});save({skipCloud:true});applyingRemote=false;companyToForm();cloudStatus('Sincronizzato');$('cloudInfo').textContent=`Ultimo aggiornamento cloud: ${o.updatedAt?.toDate?o.updatedAt.toDate().toLocaleString('it-IT'):'ricevuto'} • da ${o.updatedByName||'utente'}`;}catch(e){console.warn('Snapshot cloud non valido',e)}} ,err=>{console.warn(err);cloudStatus('Errore sincronizzazione')})}
async function pushCloudNow(silent=false){if(applyingRemote||!cloudStore||!cloudUser)return;if(!($('workspaceId').value||'').trim())return;let payload=JSON.stringify(cloudState());let kb=new Blob([payload]).size/1024;if(kb>850){if(!silent)alert(`Archivio cloud troppo grande (${Math.round(kb)} KB). In questa versione il limite operativo è 850 KB; i prezzari grandi verranno separati nella versione desktop.`);return}try{await workspaceRef().set({snapshotJson:payload,updatedAt:firebase.firestore.FieldValue.serverTimestamp(),updatedBy:cloudUser.uid,updatedByName:cloudDisplayName(),version:3},{merge:true});cloudStatus('Sincronizzato');if(!silent)$('cloudInfo').textContent=`Dati inviati al cloud (${Math.round(kb)} KB).`;}catch(e){console.warn(e);cloudStatus('Errore upload');if(!silent)alert('Errore durante il salvataggio cloud: '+e.message)}}
function queueCloudPush(){if(applyingRemote||!cloudUser||!cloudStore)return;clearTimeout(cloudPushTimer);cloudPushTimer=setTimeout(()=>pushCloudNow(true),1200)}
async function pullCloudNow(){if(!cloudStore||!cloudUser)return alert('Accedi prima al cloud.');try{let snap=await workspaceRef().get();if(!snap.exists)return alert('Workspace ancora vuoto.');let remote=JSON.parse(snap.data().snapshotJson||'{}');if(!confirm('Sostituire i dati locali con quelli del cloud?'))return;applyingRemote=true;Object.keys(cloudState()).forEach(k=>{if(remote[k]!==undefined)db[k]=remote[k]});save({skipCloud:true});applyingRemote=false;companyToForm();alert('Dati cloud scaricati.')}catch(e){alert('Errore download cloud: '+e.message)}}
async function createSharedVargaAccount(email,password){
 email=String(email||'').trim().toLowerCase();password=String(password||'');
 if(!/^\S+@\S+\.\S+$/.test(email))throw Object.assign(Error('Inserisci un indirizzo email valido.'),{code:'auth/invalid-email'});
 if(password.length<10)throw Object.assign(Error('La password deve contenere almeno 10 caratteri.'),{code:'auth/weak-password-varga'});
 if(!cloudAuth&&!initCloud())throw Error('Servizio di accesso non disponibile.');
 if(cloudAuth.currentUser)await cloudAuth.signOut();
 await prepareAuthPersistence();
 const credential=await cloudAuth.createUserWithEmailAndPassword(email,password);
 if(typeof window.createPendingCantieriProfile==='function')await window.createPendingCantieriProfile(credential.user);
 let verificationSent=false;
 try{if(credential.user.emailVerified!==true){await credential.user.sendEmailVerification();verificationSent=true}}catch(error){console.warn('Invio verifica email non riuscito',error)}
 pendingLoginNotice=verificationSent?'Account creato. Controlla la tua email, verifica l’indirizzo e attendi l’approvazione in Varga Cantieri.':'Account creato. Attendi l’approvazione in Varga Cantieri; se necessario richiedi nuovamente l’email di verifica.';
 await cloudAuth.signOut();
 return true;
}
$('saveCloudConfig').onclick=()=>{let cfg=parseFirebaseConfig()||DEFAULT_FIREBASE_CONFIG;cloudCfg.firebaseConfig=cfg;cloudCfg.workspaceId=$('workspaceId').value.trim()||'varga-azienda';cloudCfg.displayName=$('displayName').value.trim();S.set('vg_cloudConfig',cloudCfg);location.reload()};
$('disconnectCloud').onclick=()=>{if(confirm('Ripristinare la configurazione Firebase predefinita?')){S.set('vg_cloudConfig',{firebaseConfig:DEFAULT_FIREBASE_CONFIG,workspaceId:'varga-azienda'});location.reload()}};
if($('loginGoogleCloud'))$('loginGoogleCloud').onclick=async()=>{try{await loginWithGoogle()}catch(e){alert(friendlyAuthError(e))}};
$('loginCloud').onclick=async()=>{try{await loginWithEmail($('authEmail').value.trim(),$('authPassword').value);$('authPassword').value=''}catch(e){alert(friendlyAuthError(e))}};
$('registerCloud').onclick=async()=>{try{await createSharedVargaAccount($('authEmail').value,$('authPassword').value);$('authPassword').value=''}catch(e){alert(friendlyAuthError(e))}};
$('logoutCloud').onclick=()=>cloudAuth?.signOut();$('pushCloud').onclick=()=>pushCloudNow(false);$('pullCloud').onclick=pullCloudNow;
$('loginForm').onsubmit=async event=>{event.preventDefault();loginMessage();setLoginBusy(true);try{await loginWithEmail($('loginEmail').value.trim(),$('loginPassword').value);$('loginPassword').value=''}catch(e){showLogin(friendlyAuthError(e),true)}};
$('loginGoogleButton').onclick=async()=>{loginMessage();setLoginBusy(true);try{await loginWithGoogle()}catch(e){showLogin(friendlyAuthError(e),true)}};
$('createLoginAccount').onclick=async()=>{const email=$('loginEmail').value,password=$('loginPassword').value;loginMessage();setLoginBusy(true);try{await createSharedVargaAccount(email,password);$('loginPassword').value=''}catch(e){showLogin(friendlyAuthError(e),true)}};
$('forgotPassword').onclick=async()=>{const email=$('loginEmail').value.trim();if(!email)return loginMessage('Inserisci prima la tua email.',true);try{if(!cloudAuth&&!initCloud())return;await cloudAuth.sendPasswordResetEmail(email);loginMessage('Ti abbiamo inviato il link per reimpostare la password.')}catch(e){loginMessage(friendlyAuthError(e),true)}};
$('sidebarLogout').onclick=()=>cloudAuth?.signOut();
loadCloudFields();initCloud();

companyToForm();refresh();clearQuote();getHandle().then(h=>{folderHandle=h;if(h){db.meta.backupFolder=h.name;S.set('vg_meta',db.meta);refresh()}}).catch(()=>{});

if($('vcFullFile'))$('vcFullFile').onchange=async e=>{let f=e.target.files?.[0];if(!f)return;try{let payload=JSON.parse(await f.text()),c=importFullVarga(payload);refreshVcCounts();$('vcSyncInfo').textContent=`Backup completo importato: ${c.total} elementi nuovi/modificati.`;alert(`Importazione Varga Cantieri completata.\nCommesse: ${db.vcCommesse.length}\nImpianti: ${db.vcImpianti.length}\nSquadre: ${db.vcSquadre.length}\nOre/attività: ${db.vcOre.length}\nSegnalazioni: ${db.vcSegnalazioni.length}\nUtenti: ${db.vcUtenti.length}`)}catch(err){alert('Backup Varga Cantieri non valido: '+err.message)}};
setTimeout(refreshVcCounts,0);
