// backup: download + folder via File System Access API, handle kept in IndexedDB
function backupPayload(){return{app:'Varga Gestionale',version:2,createdAt:new Date().toISOString(),data:db}}function downloadBackup(){let blob=new Blob([JSON.stringify(backupPayload(),null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`Varga-Gestionale-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href);db.meta.lastBackup=new Date().toLocaleString('it-IT');S.set('vg_meta',db.meta);refresh()}$('exportBackup').onclick=downloadBackup;$('importBackup').onchange=async e=>{let f=e.target.files?.[0];if(!f)return;try{let o=JSON.parse(await f.text());if(!o.data)throw Error();Object.assign(db,o.data);save();companyToForm();clearQuote();alert('Backup ripristinato.')}catch{alert('Backup non valido.')}};
let folderHandle=null;function idb(){return new Promise((res,rej)=>{let r=indexedDB.open('varga-gestionale',1);r.onupgradeneeded=()=>r.result.createObjectStore('kv');r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}async function setHandle(h){let d=await idb();return new Promise((res,rej)=>{let t=d.transaction('kv','readwrite');t.objectStore('kv').put(h,'backupFolder');t.oncomplete=res;t.onerror=()=>rej(t.error)})}async function getHandle(){let d=await idb();return new Promise((res,rej)=>{let r=d.transaction('kv').objectStore('kv').get('backupFolder');r.onsuccess=()=>res(r.result||null);r.onerror=()=>rej(r.error)})}async function writeFolder(silent=false){if(!folderHandle)folderHandle=await getHandle();if(!folderHandle){if(!silent)alert('Scegli prima una cartella.');return}try{let perm=await folderHandle.queryPermission({mode:'readwrite'});if(perm!=='granted'&&!silent)perm=await folderHandle.requestPermission({mode:'readwrite'});if(perm!=='granted')return;let fh=await folderHandle.getFileHandle('Varga-Gestionale-backup.json',{create:true}),w=await fh.createWritable();await w.write(JSON.stringify(backupPayload(),null,2));await w.close();db.meta.lastBackup=new Date().toLocaleString('it-IT');db.meta.backupFolder=folderHandle.name;S.set('vg_meta',db.meta);if(!silent){refresh();alert('Backup completato nella cartella scelta.')}}catch(err){console.warn(err);if(!silent)alert('Non riesco a scrivere nella cartella selezionata.')}}async function autoFolderBackup(){try{if(folderHandle||await getHandle())writeFolder(true)}catch{}}$('chooseFolder').onclick=async()=>{if(!window.showDirectoryPicker)return alert('Questa funzione richiede Chrome o Edge su Windows.');try{folderHandle=await showDirectoryPicker({mode:'readwrite'});await setHandle(folderHandle);db.meta.backupFolder=folderHandle.name;S.set('vg_meta',db.meta);refresh()}catch{}};$('backupNow').onclick=()=>writeFolder(false);function updateBackupInfo(){$('lastBackup').textContent=db.meta.lastBackup||'Mai';$('backupDest').textContent=db.meta.backupFolder||'Non collegata';$('folderInfo').textContent=db.meta.backupFolder?`Cartella collegata: ${db.meta.backupFolder}`:'Nessuna cartella collegata.';$('recordCount').textContent=['clients','quotes','jobs','invoices','expenses','deadlines','documents','entries','cantieriRows','consuntivi','vcCommesse','vcImpianti','vcSquadre','vcOre','vcSegnalazioni','vcUtenti','vcRecords'].reduce((s,k)=>s+db[k].length,0)}
// Cloud multiutente: Firestore conserva uno snapshot del gestionale; Drive resta archivio file.
const cloudCfg=S.get('vg_cloudConfig',{});let cloudApp=null,cloudAuth=null,cloudStore=null,cloudFunctions=null,cloudUser=null,cloudUnsub=null,cloudPushTimer=null,applyingRemote=false;
function cloudDisplayName(){return $('displayName')?.value.trim()||cloudCfg.displayName||cloudUser?.email||'Operatore'}
function cloudStatus(text){if($('cloudStatus'))$('cloudStatus').textContent=text;if($('cloudUser'))$('cloudUser').textContent=cloudUser?.email||'Non connesso';if($('cloudWorkspaceLabel'))$('cloudWorkspaceLabel').textContent=($('workspaceId')?.value||cloudCfg.workspaceId||'-')}
function cloudState(){return{priceLists:db.priceLists,entries:db.entries,clients:db.clients,quotes:db.quotes,jobs:db.jobs,invoices:db.invoices,expenses:db.expenses,deadlines:db.deadlines,documents:db.documents,consuntivi:db.consuntivi,company:db.company}}
function loadCloudFields(){if(cloudCfg.firebaseConfig)$('firebaseConfig').value=JSON.stringify(cloudCfg.firebaseConfig,null,2);$('workspaceId').value=cloudCfg.workspaceId||'varga-azienda';$('displayName').value=cloudCfg.displayName||'';cloudStatus(cloudCfg.firebaseConfig?'Configurato':'Non configurato')}
function parseFirebaseConfig(){try{return JSON.parse($('firebaseConfig').value.trim())}catch{return null}}
function initCloud(){let cfg=cloudCfg.firebaseConfig;if(!cfg||typeof firebase==='undefined')return false;try{cloudApp=firebase.apps.find(a=>a.name==='vargaGestionale')||firebase.initializeApp(cfg,'vargaGestionale');cloudAuth=cloudApp.auth();cloudStore=cloudApp.firestore();cloudFunctions=typeof cloudApp.functions==='function'?cloudApp.functions('europe-west1'):null;cloudAuth.onAuthStateChanged(u=>{cloudUser=u||null;cloudStatus(u?'Connesso':'Configurato');if(u)startCloudRealtime();else stopCloudRealtime()});return true}catch(e){console.warn(e);cloudStatus('Errore configurazione');return false}}
function workspaceRef(){let id=($('workspaceId').value||cloudCfg.workspaceId||'varga-azienda').trim();return cloudStore.collection('vargaGestionaleWorkspaces').doc(id)}
function stopCloudRealtime(){if(cloudUnsub){cloudUnsub();cloudUnsub=null}}
function startCloudRealtime(){if(!cloudStore||!cloudUser)return;stopCloudRealtime();cloudUnsub=workspaceRef().onSnapshot(snap=>{if(!snap.exists)return;let o=snap.data();if(o.updatedBy===cloudUser.uid)return;try{let remote=JSON.parse(o.snapshotJson||'{}');applyingRemote=true;Object.keys(cloudState()).forEach(k=>{if(remote[k]!==undefined)db[k]=remote[k]});save({skipCloud:true});applyingRemote=false;companyToForm();cloudStatus('Sincronizzato');$('cloudInfo').textContent=`Ultimo aggiornamento cloud: ${o.updatedAt?.toDate?o.updatedAt.toDate().toLocaleString('it-IT'):'ricevuto'} • da ${o.updatedByName||'utente'}`;}catch(e){console.warn('Snapshot cloud non valido',e)}} ,err=>{console.warn(err);cloudStatus('Errore sincronizzazione')})}
async function pushCloudNow(silent=false){if(applyingRemote||!cloudStore||!cloudUser)return;if(!($('workspaceId').value||'').trim())return;let payload=JSON.stringify(cloudState());let kb=new Blob([payload]).size/1024;if(kb>850){if(!silent)alert(`Archivio cloud troppo grande (${Math.round(kb)} KB). In questa versione il limite operativo è 850 KB; i prezzari grandi verranno separati nella versione desktop.`);return}try{await workspaceRef().set({snapshotJson:payload,updatedAt:firebase.firestore.FieldValue.serverTimestamp(),updatedBy:cloudUser.uid,updatedByName:cloudDisplayName(),version:3},{merge:true});cloudStatus('Sincronizzato');if(!silent)$('cloudInfo').textContent=`Dati inviati al cloud (${Math.round(kb)} KB).`;}catch(e){console.warn(e);cloudStatus('Errore upload');if(!silent)alert('Errore durante il salvataggio cloud: '+e.message)}}
function queueCloudPush(){if(applyingRemote||!cloudUser||!cloudStore)return;clearTimeout(cloudPushTimer);cloudPushTimer=setTimeout(()=>pushCloudNow(true),1200)}
async function pullCloudNow(){if(!cloudStore||!cloudUser)return alert('Accedi prima al cloud.');try{let snap=await workspaceRef().get();if(!snap.exists)return alert('Workspace ancora vuoto.');let remote=JSON.parse(snap.data().snapshotJson||'{}');if(!confirm('Sostituire i dati locali con quelli del cloud?'))return;applyingRemote=true;Object.keys(cloudState()).forEach(k=>{if(remote[k]!==undefined)db[k]=remote[k]});save({skipCloud:true});applyingRemote=false;companyToForm();alert('Dati cloud scaricati.')}catch(e){alert('Errore download cloud: '+e.message)}}
$('saveCloudConfig').onclick=()=>{let cfg=parseFirebaseConfig();if(!cfg||!cfg.apiKey||!cfg.projectId)return alert('Configurazione Firebase non valida.');cloudCfg.firebaseConfig=cfg;cloudCfg.workspaceId=$('workspaceId').value.trim()||'varga-azienda';cloudCfg.displayName=$('displayName').value.trim();S.set('vg_cloudConfig',cloudCfg);location.reload()};
$('disconnectCloud').onclick=()=>{if(confirm('Rimuovere la configurazione cloud da questo PC?')){S.set('vg_cloudConfig',{});location.reload()}};
if($('loginGoogleCloud'))$('loginGoogleCloud').onclick=async()=>{if(!cloudAuth)return alert('Configura prima Firebase.');try{let provider=new firebase.auth.GoogleAuthProvider();await cloudAuth.signInWithPopup(provider)}catch(e){alert('Accesso Google non riuscito: '+e.message)}};
$('loginCloud').onclick=async()=>{if(!cloudAuth)return alert('Configura prima Firebase.');try{await cloudAuth.signInWithEmailAndPassword($('authEmail').value.trim(),$('authPassword').value);$('authPassword').value=''}catch(e){alert('Accesso non riuscito: '+e.message)}};
$('registerCloud').onclick=async()=>{if(!cloudAuth)return alert('Configura prima Firebase.');try{await cloudAuth.createUserWithEmailAndPassword($('authEmail').value.trim(),$('authPassword').value);$('authPassword').value='';alert('Utente creato e connesso.')}catch(e){alert('Creazione utente non riuscita: '+e.message)}};
$('logoutCloud').onclick=()=>cloudAuth?.signOut();$('pushCloud').onclick=()=>pushCloudNow(false);$('pullCloud').onclick=pullCloudNow;
loadCloudFields();initCloud();

companyToForm();refresh();clearQuote();getHandle().then(h=>{folderHandle=h;if(h){db.meta.backupFolder=h.name;S.set('vg_meta',db.meta);refresh()}}).catch(()=>{});

if($('vcFullFile'))$('vcFullFile').onchange=async e=>{let f=e.target.files?.[0];if(!f)return;try{let payload=JSON.parse(await f.text()),c=importFullVarga(payload);refreshVcCounts();$('vcSyncInfo').textContent=`Backup completo importato: ${c.total} elementi nuovi/modificati.`;alert(`Importazione Varga Cantieri completata.\nCommesse: ${db.vcCommesse.length}\nImpianti: ${db.vcImpianti.length}\nSquadre: ${db.vcSquadre.length}\nOre/attività: ${db.vcOre.length}\nSegnalazioni: ${db.vcSegnalazioni.length}\nUtenti: ${db.vcUtenti.length}`)}catch(err){alert('Backup Varga Cantieri non valido: '+err.message)}};
setTimeout(refreshVcCounts,0);
