function rawRecordKey(r){return String(r?.sourcePath||`${r?.rootCollection||'unknown'}/${r?.id||''}`)}
function stableData(v){if(Array.isArray(v))return v.map(stableData);if(v&&typeof v==='object'){let o={};Object.keys(v).sort().forEach(k=>{if(k!=='syncedAt')o[k]=stableData(v[k])});return o}return v}
function mergeRawVcRecords(records){let map=new Map((db.vcRecords||[]).map(r=>[rawRecordKey(r),r])),created=0,updated=0,unchanged=0;(records||[]).forEach(r=>{let k=rawRecordKey(r);if(!k)return;let next={...r,sourcePath:k,syncedAt:new Date().toISOString()},old=map.get(k);if(!old){map.set(k,next);created++;return}if(JSON.stringify(stableData(old.data))!==JSON.stringify(stableData(next.data))){map.set(k,next);updated++}else unchanged++});db.vcRecords=[...map.values()];return{created,updated,unchanged,changed:created+updated}}
function firstVal(o,names){for(const n of names){let k=Object.keys(o||{}).find(x=>norm(x)===norm(n));if(k!=null&&o[k]!=null&&String(o[k]).trim()!=='')return o[k]}return''}
function sourceCommessaPath(path){let p=String(path||'').split('/');let i=p.indexOf('commesse');return i>=0&&p[i+1]?`commesse/${p[i+1]}`:''}
function findJobForRecord(o){let cp=sourceCommessaPath(o.vcSourceId||o.sourcePath);if(cp){let j=db.jobs.find(x=>x.vcSourceId===cp);if(j)return j}let code=String(firstVal(o,['codiceCommessa','codice commessa','commessaCode','code'])||'').trim(),name=String(firstVal(o,['commessa','nomeCommessa','commessaNome'])||'').trim();return db.jobs.find(j=>(code&&String(j.code)===code)||(name&&norm(j.title)===norm(name)))||null}
function ensureClientFromCommessa(c,job){let name=String(firstVal(c,['cliente','client','clienteNome','ragioneSociale','committente'])||'').trim();if(!name)return null;let vat=String(firstVal(c,['piva','partitaIva','vat','codiceFiscale','cf'])||'').trim(),email=String(firstVal(c,['clienteEmail','emailCliente'])||'').trim();let client=db.clients.find(x=>(vat&&x.vat===vat)||norm(x.name)===norm(name));if(!client){client={id:uid(),name,vat,address:String(firstVal(c,['clienteIndirizzo','indirizzoCliente'])||''),city:String(firstVal(c,['clienteComune','comuneCliente'])||''),email,phone:String(firstVal(c,['clienteTelefono','telefonoCliente'])||''),priceListId:'',notes:'Importato da Varga Cantieri',vcSourceId:c.vcSourceId};db.clients.push(client)}if(job&&!job.clientId)job.clientId=client.id;return client}
function isDoneData(o){let s=norm(String(firstVal(o,['stato','status','esito','fatto','finito','terminato'])||''));return s.includes('fatto')||s.includes('finit')||s.includes('terminat')||s.includes('complet')||firstVal(o,['doneAt','fattoAt','completedAt','dataFatto'])!==''}
function consuntivoFromRecord(o){if(!isDoneData(o))return false;let job=findJobForRecord(o),impianto=String(firstVal(o,['impianto','denominazioneImpianto','nomeImpianto','cantiere'])||''),idSap=String(firstVal(o,['idSap','ID SAP','sap'])||''),data=String(firstVal(o,['data','dataFatto','doneDate','completedAt','fattoAt'])||''),lavorazione=String(firstVal(o,['lavorazione','attivita','attività','descrizione','tipoLavoro'])||''),operatore=String(firstVal(o,['operatore','utente','userName','squadra','operatorName'])||''),ore=firstVal(o,['ore','oreLavorate','hours']),qta=firstVal(o,['quantita','quantità','qta']),um=String(firstVal(o,['unita','unità','um','u.m.'])||''),note=String(firstVal(o,['note','nota','notes'])||'');if(!job&&!impianto&&!idSap)return false;let sid=o.vcSourceId||o.sourcePath,existing=db.consuntivi.find(x=>x.sourceId===sid),probe={lavorazione,impianto},pe=matchPriceEntry(probe),base={sourceId:sid,commessa:job?.title||String(firstVal(o,['commessa','nomeCommessa'])||''),codiceCommessa:job?.code||String(firstVal(o,['codiceCommessa','codice commessa'])||''),impianto,idSap,comune:String(firstVal(o,['comune','ubicazioneComune'])||''),data,ora:String(firstVal(o,['ora','oraFatto'])||''),operatore,lavorazione,quantita:qta||1,unita:um||pe?.unit||'',ore,note,priceEntryId:pe?.id||'',priceCode:pe?.code||'',prezzo:pe?.price||0,importo:pe?Number(qta||1)*Number(pe.price||0):0};if(existing){if(existing.status!=='Contabilizzato')Object.assign(existing,base);return false}db.consuntivi.push({id:uid(),...base,status:'Da verificare',createdAt:new Date().toISOString()});return true}
function mapSnapshotRecords(records,manifest={}){
 let groups={};(records||[]).forEach(r=>(groups[r.rootCollection]??=[]).push(r));const unpack=list=>(list||[]).map(r=>({...(r.data||{}),id:(r.data&&r.data.id)||r.id,vcSourceId:r.sourcePath,vcRootCollection:r.rootCollection}));let delta=mergeRawVcRecords(records),mapped=0,newCons=0;
 const mappings=[['impianti','vcImpianti'],['personale','vcUtenti'],['oreReports','vcOre'],['oreApprovalRequests','vcOre'],['squadre','vcSquadre'],['squadreCommesse','vcSquadre'],['squadreStorico','vcSquadre']];mappings.forEach(([root,key])=>{if(groups[root])mapped+=upsertBySource(db[key],unpack(groups[root]))});
 ['documents','posDocuments'].forEach(root=>{if(groups[root])mapped+=upsertBySource(db.documents,unpack(groups[root]).map(d=>({id:d.id||uid(),name:d.name||d.fileName||d.title||'Documento Varga Cantieri',category:d.category||d.type||root,driveUrl:d.driveUrl||d.url||d.webViewLink||'',notes:d.notes||'',clientId:'',jobId:'',addedBy:d.addedBy||d.userName||'Varga Cantieri',vcSourceId:d.vcSourceId,vcRootCollection:root}))) });Object.entries(groups).filter(([root])=>/segnal/i.test(root)).forEach(([,rows])=>{mapped+=upsertBySource(db.vcSegnalazioni,unpack(rows))});
 if(groups.commesse){let all=unpack(groups.commesse),rootCommesse=all.filter(x=>String(x.vcSourceId||'').split('/').length===2);mapped+=upsertBySource(db.vcCommesse,rootCommesse);rootCommesse.forEach(c=>{let existing=db.jobs.find(j=>j.vcSourceId===c.vcSourceId||j.sourceId===c.id),patch={title:c.title||c.name||c.nome||c.commessa||'Commessa Varga Cantieri',code:c.code||c.codice||c.codiceCommessa||'',clientId:existing?.clientId||'',site:c.site||c.cantiere||c.comune||'',start:c.start||c.dataInizio||'',end:c.end||c.dataFine||'',value:Number(c.value||c.importo||0),status:c.status||c.stato||'Attiva',vcSourceId:c.vcSourceId,sourceId:c.id};if(existing)Object.assign(existing,patch);else{existing={id:uid(),...patch};db.jobs.push(existing)}ensureClientFromCommessa(c,existing)});all.forEach(o=>{if(consuntivoFromRecord(o))newCons++})}
 Object.values(groups).flat().map(r=>({...(r.data||{}),vcSourceId:r.sourcePath,vcRootCollection:r.rootCollection})).forEach(o=>{if(consuntivoFromRecord(o))newCons++});
 db.meta.vcLastSync=new Date().toLocaleString('it-IT');db.meta.vcSnapshotId=manifest.snapshotId||'';db.meta.vcSnapshotGeneratedAt=manifest.generatedAt||'';db.meta.vcSnapshotCounts=manifest.counts||{};save();refreshVcCounts();return{...delta,mapped,newCons,records:(records||[]).length};
}
async function syncVargaFromCloud(){if(!cloudFunctions||!cloudUser)throw Error('Accedi al Cloud con lo stesso progetto Firebase di Varga Cantieri.');let rebuild=cloudFunctions.httpsCallable('rebuildVargaGestionaleSnapshot'),manifestFn=cloudFunctions.httpsCallable('getVargaGestionaleSnapshotManifest'),chunkFn=cloudFunctions.httpsCallable('getVargaGestionaleSnapshotChunk'),manifest=null;$('vcSyncInfo').textContent='Creo lo snapshot aggiornato di Varga Cantieri...';try{manifest=(await rebuild({})).data}catch(err){let code=String(err?.code||'');if(!/permission-denied/i.test(code))throw err;$('vcSyncInfo').textContent='Uso l’ultimo snapshot disponibile...';manifest=(await manifestFn({})).data}if(!manifest||manifest.available===false||!manifest.snapshotId)throw Error('Nessuno snapshot Varga Cantieri disponibile.');let records=[];for(let i=0;i<Number(manifest.chunkCount||0);i++){$('vcSyncInfo').textContent=`Importazione Varga Cantieri: blocco ${i+1}/${manifest.chunkCount}...`;let chunk=(await chunkFn({snapshotId:manifest.snapshotId,index:i})).data;records.push(...(chunk.records||[]))}let result=mapSnapshotRecords(records,manifest);$('vcSyncInfo').textContent=`${result.records} controllati • ${result.created} nuovi • ${result.updated} modificati • ${result.unchanged} invariati • ${result.newCons} nuovi consuntivi.`;return result}
if($('syncVcNow'))$('syncVcNow').onclick=async()=>{let url=$('vcEndpoint').value.trim();$('vcSyncInfo').textContent='Avvio sincronizzazione...';try{if(cloudFunctions&&cloudUser){await syncVargaFromCloud();return}if(!url)throw Error('Configura Firebase e accedi al Cloud, oppure inserisci un endpoint JSON di fallback.');let res=await fetch(url,{cache:'no-store'});if(!res.ok)throw Error(`HTTP ${res.status}`);let data=await res.json();if(Array.isArray(data)){let r=ingestVcRows(data);$('vcSyncInfo').textContent=`Sincronizzato Gestione Commesse: ${r.changed} variazioni, ${r.created} nuovi consuntivi.`}else{let c=importFullVarga(data);refreshVcCounts();$('vcSyncInfo').textContent=`Sincronizzazione completa: ${c.total} elementi nuovi/modificati.`}}catch(err){console.warn(err);$('vcSyncInfo').textContent='Errore sincronizzazione: '+err.message}};
if($('consFilter'))$('consFilter').onchange=refresh;if($('consSearch'))$('consSearch').oninput=refresh;
if($('exportConsCsv'))$('exportConsCsv').onclick=()=>{let rows=[['Commessa','Codice commessa','Impianto','ID SAP','Comune','Data','Ora','Operatore','Lavorazione','Quantità','U.M.','Ore','Codice prezzo','Prezzo','Importo','Stato'],...db.consuntivi.map(c=>[c.commessa,c.codiceCommessa,c.impianto,c.idSap,c.comune,c.data,c.ora,c.operatore,c.lavorazione,c.quantita,c.unita,c.ore,c.priceCode,c.prezzo,c.importo,c.status])],csv=rows.map(r=>r.map(v=>'"'+String(v??'').replace(/"/g,'""')+'"').join(';')).join('\n'),a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8'}));a.download=`Varga-Consuntivi-${new Date().toISOString().slice(0,10)}.csv`;a.click();URL.revokeObjectURL(a.href)};