function rawRecordKey(r){return String(r?.sourcePath||`${r?.rootCollection||'unknown'}/${r?.id||''}`)}
function mergeRawVcRecords(records){let map=new Map((db.vcRecords||[]).map(r=>[rawRecordKey(r),r]));let changed=0;(records||[]).forEach(r=>{let k=rawRecordKey(r);if(!k)return;let next={...r,sourcePath:k,syncedAt:new Date().toISOString()};let old=map.get(k);if(!old||JSON.stringify(old.data)!==JSON.stringify(next.data)){map.set(k,next);changed++}});db.vcRecords=[...map.values()];return changed}
function mapSnapshotRecords(records,manifest={}){
 let groups={};(records||[]).forEach(r=>(groups[r.rootCollection]??=[]).push(r));
 const unpack=list=>(list||[]).map(r=>({...(r.data||{}),id:(r.data&&r.data.id)||r.id,vcSourceId:r.sourcePath,vcRootCollection:r.rootCollection}));
 let total=mergeRawVcRecords(records),mapped=0;
 const mappings=[['impianti','vcImpianti'],['personale','vcUtenti'],['oreReports','vcOre'],['oreApprovalRequests','vcOre'],['squadre','vcSquadre'],['squadreCommesse','vcSquadre'],['squadreStorico','vcSquadre']];
 mappings.forEach(([root,key])=>{if(groups[root])mapped+=upsertBySource(db[key],unpack(groups[root]))});
 ['documents','posDocuments'].forEach(root=>{if(groups[root])mapped+=upsertBySource(db.documents,unpack(groups[root]).map(d=>({id:d.id||uid(),name:d.name||d.fileName||d.title||'Documento Varga Cantieri',category:d.category||d.type||root,driveUrl:d.driveUrl||d.url||d.webViewLink||'',notes:d.notes||'',clientId:'',jobId:'',addedBy:d.addedBy||d.userName||'Varga Cantieri',vcSourceId:d.vcSourceId,vcRootCollection:root}))) });
 Object.entries(groups).filter(([root])=>/segnal/i.test(root)).forEach(([,rows])=>{mapped+=upsertBySource(db.vcSegnalazioni,unpack(rows))});
 // Tutti i documenti annidati sotto commesse restano nel registro grezzo; le commesse radice vengono anche mappate nel gestionale.
 if(groups.commesse){let rootCommesse=unpack(groups.commesse).filter(x=>String(x.vcSourceId||'').split('/').length===2);mapped+=upsertBySource(db.vcCommesse,rootCommesse);rootCommesse.forEach(c=>{let existing=db.jobs.find(j=>j.vcSourceId===c.vcSourceId||j.sourceId===c.id);let patch={title:c.title||c.name||c.nome||c.commessa||'Commessa Varga Cantieri',code:c.code||c.codice||c.codiceCommessa||'',clientId:existing?.clientId||'',site:c.site||c.cantiere||c.comune||'',start:c.start||c.dataInizio||'',end:c.end||c.dataFine||'',value:Number(c.value||c.importo||0),status:c.status||c.stato||'Attiva',vcSourceId:c.vcSourceId,sourceId:c.id};if(existing)Object.assign(existing,patch);else db.jobs.push({id:uid(),...patch})})}
 db.meta.vcLastSync=new Date().toLocaleString('it-IT');db.meta.vcSnapshotId=manifest.snapshotId||'';db.meta.vcSnapshotGeneratedAt=manifest.generatedAt||'';db.meta.vcSnapshotCounts=manifest.counts||{};save();refreshVcCounts();return{total,mapped,records:(records||[]).length};
}
async function syncVargaFromCloud(){
 if(!cloudFunctions||!cloudUser)throw Error('Accedi al Cloud con lo stesso progetto Firebase di Varga Cantieri.');
 let rebuild=cloudFunctions.httpsCallable('rebuildVargaGestionaleSnapshot'),manifestFn=cloudFunctions.httpsCallable('getVargaGestionaleSnapshotManifest'),chunkFn=cloudFunctions.httpsCallable('getVargaGestionaleSnapshotChunk'),manifest=null;
 $('vcSyncInfo').textContent='Creo lo snapshot aggiornato di Varga Cantieri...';
 try{manifest=(await rebuild({})).data}catch(err){let code=String(err?.code||'');if(!/permission-denied/i.test(code))throw err;$('vcSyncInfo').textContent='Uso l’ultimo snapshot disponibile...';manifest=(await manifestFn({})).data}
 if(!manifest||manifest.available===false||!manifest.snapshotId)throw Error('Nessuno snapshot Varga Cantieri disponibile. Accedi come amministratore e genera il primo snapshot.');
 let records=[];for(let i=0;i<Number(manifest.chunkCount||0);i++){$('vcSyncInfo').textContent=`Importazione Varga Cantieri: blocco ${i+1}/${manifest.chunkCount}...`;let chunk=(await chunkFn({snapshotId:manifest.snapshotId,index:i})).data;records.push(...(chunk.records||[]))}
 let result=mapSnapshotRecords(records,manifest);$('vcSyncInfo').textContent=`Sincronizzazione completa: ${result.records} record letti, ${result.total} nuovi/modificati. Snapshot ${manifest.snapshotId}.`;return result;
}
if($('syncVcNow'))$('syncVcNow').onclick=async()=>{let url=$('vcEndpoint').value.trim();$('vcSyncInfo').textContent='Avvio sincronizzazione...';try{if(cloudFunctions&&cloudUser){await syncVargaFromCloud();return}if(!url)throw Error('Configura Firebase e accedi al Cloud, oppure inserisci un endpoint JSON di fallback.');let res=await fetch(url,{cache:'no-store'});if(!res.ok)throw Error(`HTTP ${res.status}`);let data=await res.json();if(Array.isArray(data)){let r=ingestVcRows(data);$('vcSyncInfo').textContent=`Sincronizzato Gestione Commesse: ${r.changed} variazioni, ${r.created} nuovi consuntivi.`}else{let c=importFullVarga(data);refreshVcCounts();$('vcSyncInfo').textContent=`Sincronizzazione completa: ${c.total} elementi nuovi/modificati. Commesse ${db.vcCommesse.length}, impianti ${db.vcImpianti.length}, ore ${db.vcOre.length}.`}}catch(err){console.warn(err);$('vcSyncInfo').textContent='Errore sincronizzazione: '+err.message}};
if($('consFilter'))$('consFilter').onchange=refresh;if($('consSearch'))$('consSearch').oninput=refresh;
if($('exportConsCsv'))$('exportConsCsv').onclick=()=>{let rows=[['Commessa','Codice commessa','Impianto','ID SAP','Comune','Data','Ora','Operatore','Lavorazione','Quantità','U.M.','Ore','Codice prezzo','Prezzo','Importo','Stato'],...db.consuntivi.map(c=>[c.commessa,c.codiceCommessa,c.impianto,c.idSap,c.comune,c.data,c.ora,c.operatore,c.lavorazione,c.quantita,c.unita,c.ore,c.priceCode,c.prezzo,c.importo,c.status])],csv=rows.map(r=>r.map(v=>'"'+String(v??'').replace(/"/g,'""')+'"').join(';')).join('\n'),a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8'}));a.download=`Varga-Consuntivi-${new Date().toISOString().slice(0,10)}.csv`;a.click();URL.revokeObjectURL(a.href)};
