const VG_ENTRY_DB='varga-gestionale-large-data',VG_ENTRY_STORE='priceEntries',VG_ENTRY_LIMIT=2000;
function entryDatabase(){return new Promise((resolve,reject)=>{if(!window.indexedDB)return reject(new Error('IndexedDB non disponibile'));const request=indexedDB.open(VG_ENTRY_DB,1);request.onupgradeneeded=()=>{if(!request.result.objectStoreNames.contains(VG_ENTRY_STORE))request.result.createObjectStore(VG_ENTRY_STORE)};request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)})}
async function storeLargeEntries(rows){const database=await entryDatabase();return new Promise((resolve,reject)=>{const transaction=database.transaction(VG_ENTRY_STORE,'readwrite');transaction.objectStore(VG_ENTRY_STORE).put(rows,'all');transaction.oncomplete=()=>{database.close();resolve()};transaction.onerror=()=>{database.close();reject(transaction.error)}})}
async function readLargeEntries(){try{const database=await entryDatabase();return await new Promise((resolve,reject)=>{const transaction=database.transaction(VG_ENTRY_STORE,'readonly'),request=transaction.objectStore(VG_ENTRY_STORE).get('all');request.onsuccess=()=>{database.close();resolve(Array.isArray(request.result)?request.result:[])};request.onerror=()=>{database.close();reject(request.error)}})}catch(error){console.warn('Archivio prezziari non disponibile',error);return[]}}
const S={get(k,d){try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}},set(k,v){if(k==='vg_entries'&&Array.isArray(v)&&v.length>VG_ENTRY_LIMIT){localStorage.setItem(k,'[]');storeLargeEntries(v).catch(error=>console.error('Salvataggio prezziario grande non riuscito',error));return}localStorage.setItem(k,JSON.stringify(v));if(k==='vg_entries'&&Array.isArray(v))storeLargeEntries(v).catch(()=>{})}};
const db={priceLists:S.get('vg_priceLists',[{id:'pl-default',name:'Prezzario aziendale'}]),entries:S.get('vg_entries',[{id:'e1',priceListId:'pl-default',code:'VERDE.001',description:'Potatura di alberi e arbusti con raccolta del materiale di risulta',unit:'cad',price:85},{id:'e2',priceListId:'pl-default',code:'VERDE.002',description:'Abbattimento controllato di albero ad alto fusto',unit:'cad',price:280},{id:'e3',priceListId:'pl-default',code:'VERDE.003',description:'Raccolta, carico e trasporto del materiale vegetale di risulta',unit:'m³',price:42},{id:'e4',priceListId:'pl-default',code:'VERDE.004',description:'Trattamento protettivo impregnante per elementi in legno',unit:'m²',price:18.5},{id:'e5',priceListId:'pl-default',code:'VERDE.005',description:'Fornitura e posa di elemento in legno per recinzione o staccionata',unit:'cad',price:74}]),clients:S.get('vg_clients',[]),quotes:S.get('vg_quotes',[]),jobs:S.get('vg_jobs',[]),requests:S.get('vg_requests',[]),invoices:S.get('vg_invoices',[]),expenses:S.get('vg_expenses',[]),deadlines:S.get('vg_deadlines',[]),documents:S.get('vg_documents',[]),cantieriRows:S.get('vg_cantieriRows',[]),consuntivi:S.get('vg_consuntivi',[]),vcCommesse:S.get('vg_vcCommesse',[]),vcImpianti:S.get('vg_vcImpianti',[]),vcSquadre:S.get('vg_vcSquadre',[]),vcOre:S.get('vg_vcOre',[]),vcSegnalazioni:S.get('vg_vcSegnalazioni',[]),vcUtenti:S.get('vg_vcUtenti',[]),vcRecords:S.get('vg_vcRecords',[]),company:S.get('vg_company',{}),meta:S.get('vg_meta',{})};
const $=id=>document.getElementById(id), uid=()=>crypto.randomUUID(), euro=n=>new Intl.NumberFormat('it-IT',{style:'currency',currency:'EUR'}).format(Number(n||0)), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function save(opts={}){for(const k of ['priceLists','entries','clients','quotes','jobs','requests','invoices','expenses','deadlines','documents','cantieriRows','consuntivi','vcCommesse','vcImpianti','vcSquadre','vcOre','vcSegnalazioni','vcUtenti','vcRecords','company','meta'])S.set('vg_'+k,db[k]);refresh();autoFolderBackup();if(!opts.skipCloud&&db.entries.length<=VG_ENTRY_LIMIT)queueCloudPush()}
function nav(v){document.querySelectorAll('.view').forEach(x=>x.classList.remove('active-view'));$(v).classList.add('active-view');document.querySelectorAll('.nav').forEach(x=>x.classList.toggle('active',x.dataset.view===v));refresh()}
document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>nav(b.dataset.view));document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>nav(b.dataset.go));
const opt=(arr,blank='Seleziona')=>`<option value="">${blank}</option>`+arr.map(x=>`<option value="${x.id}">${esc(x.name||x.title)}</option>`).join('');
function clientName(id){return db.clients.find(x=>x.id===id)?.name||''}function jobName(id){return db.jobs.find(x=>x.id===id)?.title||''}
function item(title,sub,right='',actions=''){return `<div class="item"><div class="item-main"><div class="item-title">${title}</div><div class="item-sub">${sub}</div></div><div class="item-actions">${right}${actions}</div></div>`}
function refresh(){
 $('kPrev').textContent=db.quotes.length;$('kCli').textContent=db.clients.length;$('kJobs').textContent=db.jobs.filter(x=>x.status!=='Terminata').length;$('kDue').textContent=euro(db.invoices.filter(x=>x.status!=='Pagata').reduce((s,x)=>s+Number(x.amount||0),0));$('kDead').textContent=db.deadlines.filter(x=>!x.done).length;
 $('qClient').innerHTML=opt(db.clients);$('docClient').innerHTML=opt(db.clients,'Nessun cliente');$('docJob').innerHTML=opt(db.jobs,'Nessuna commessa');$('cPriceList').innerHTML=opt(db.priceLists,'Prezzario predefinito');$('jClient').innerHTML=opt(db.clients);$('fClient').innerHTML=opt(db.clients);if($('ePL'))$('ePL').innerHTML=opt(db.priceLists);$('xJob').innerHTML=opt(db.jobs,'Nessuna commessa');
 $('clientsList').innerHTML=db.clients.length?db.clients.map(c=>item(esc(c.name),`${esc(c.vat||'')} ${c.city?'• '+esc(c.city):''} ${c.email?'• '+esc(c.email):''}`,`<span class="badge">${esc(db.priceLists.find(p=>p.id===c.priceListId)?.name||'')}</span>`,`<button class="mini danger" data-del-client="${c.id}">Elimina</button>`)).join(''):'<div class="empty">Nessun cliente.</div>';
 if($('entriesList'))$('entriesList').innerHTML=db.entries.length?db.entries.slice(-300).reverse().map(e=>item(`${esc(e.code)} — ${esc(e.description)}`,`${esc(db.priceLists.find(p=>p.id===e.priceListId)?.name||'')} • ${esc(e.unit)}`,`<strong>${euro(e.price)}</strong>`,`<button class="mini danger" data-del-entry="${e.id}">Elimina</button>`)).join(''):'<div class="empty">Nessuna voce.</div>';
 $('quotesList').innerHTML=db.quotes.length?db.quotes.slice().reverse().map(q=>item(`${esc(q.number)} — ${esc(q.subject||'Preventivo')}`,`${esc(q.clientName||'')} • ${esc(q.date)} • <span class="badge">${esc(q.status||'Bozza')}</span>`,`<strong>${euro(q.total)}</strong>`,`<button class="mini" data-job-from-quote="${q.id}">Crea commessa</button><button class="mini danger" data-del-quote="${q.id}">Elimina</button>`)).join(''):'<div class="empty">Nessun preventivo.</div>';
 $('jobsList').innerHTML=db.jobs.length?db.jobs.slice().reverse().map(j=>item(`${esc(j.code||'')} ${esc(j.title)}`,`${esc(clientName(j.clientId))} • ${esc(j.site||'')} • <span class="badge">${esc(j.status)}</span>`, `<strong>${euro(j.value)}</strong>`,`<button class="mini" data-cycle-job="${j.id}">Cambia stato</button><button class="mini danger" data-del-job="${j.id}">Elimina</button>`)).join(''):'<div class="empty">Nessuna commessa.</div>';
 $('invoicesList').innerHTML=db.invoices.length?db.invoices.slice().reverse().map(f=>item(`${esc(f.number||'Documento')} — ${esc(clientName(f.clientId))}`,`${esc(f.date||'')} • scad. ${esc(f.due||'-')} • <span class="badge">${esc(f.status)}</span>`,`<strong>${euro(f.amount)}</strong>`,`<button class="mini" data-pay="${f.id}">Segna pagata</button><button class="mini danger" data-del-invoice="${f.id}">Elimina</button>`)).join(''):'<div class="empty">Nessun documento.</div>';
 $('expensesList').innerHTML=db.expenses.length?db.expenses.slice().reverse().map(x=>item(`${esc(x.supplier)} — ${esc(x.category||'Spesa')}`,`${esc(x.date)} ${x.jobId?'• '+esc(jobName(x.jobId)):''}`,`<strong>${euro(x.amount)}</strong>`,`<button class="mini danger" data-del-exp="${x.id}">Elimina</button>`)).join(''):'<div class="empty">Nessuna spesa.</div>';
 const dsort=db.deadlines.slice().sort((a,b)=>String(a.date).localeCompare(String(b.date)));$('deadlinesList').innerHTML=dsort.length?dsort.map(d=>item(`${d.done?'✓ ':''}${esc(d.title)}`,`${esc(d.date)} • ${esc(d.type)} ${d.notes?'• '+esc(d.notes):''}`,`<span class="badge">${d.done?'Fatta':'Aperta'}</span>`,`<button class="mini" data-done="${d.id}">${d.done?'Riapri':'Completa'}</button><button class="mini danger" data-del-dead="${d.id}">Elimina</button>`)).join(''):'<div class="empty">Nessuna scadenza.</div>';
 $('dashDeadlines').innerHTML=dsort.filter(x=>!x.done).slice(0,6).map(d=>item(esc(d.title),`${esc(d.date)} • ${esc(d.type)}`)).join('')||'<div class="empty">Nessuna scadenza aperta.</div>';
 const dq=norm($('docSearch')?.value||'');const docs=db.documents.filter(d=>!dq||norm([d.name,d.category,d.notes,clientName(d.clientId),jobName(d.jobId)].join(' ')).includes(dq));$('documentsList').innerHTML=docs.length?docs.slice().reverse().map(d=>item(`${esc(d.name)} <span class="badge">${esc(d.category)}</span>`,`${esc(clientName(d.clientId)||'')} ${d.jobId?'• '+esc(jobName(d.jobId)):''} ${d.addedBy?'• '+esc(d.addedBy):''}`,d.driveUrl?`<a class="mini linkbtn" href="${esc(d.driveUrl)}" target="_blank" rel="noopener">Apri in Drive</a>`:'',`<button class="mini danger" data-del-doc="${d.id}">Elimina</button>`)).join(''):'<div class="empty">Nessun documento.</div>';
 const rec=[...db.quotes.slice(-3).map(x=>({t:x.date,n:'Preventivo '+x.number,s:x.clientName})),...db.jobs.slice(-3).map(x=>({t:x.start,n:'Commessa '+x.title,s:x.status}))].slice(-6).reverse();$('recentList').innerHTML=rec.map(r=>item(esc(r.n),`${esc(r.t||'')} • ${esc(r.s||'')}`)).join('')||'<div class="empty">Nessuna attività.</div>';
 if($('vcImported'))$('vcImported').textContent=db.cantieriRows.length;
 if($('vcPending'))$('vcPending').textContent=db.consuntivi.filter(x=>x.status==='Da verificare').length;
 if($('vcLastSync'))$('vcLastSync').textContent=db.meta.vcLastSync||'Mai';
 if($('vcRowsList'))$('vcRowsList').innerHTML=db.cantieriRows.length?db.cantieriRows.slice(-40).reverse().map(r=>item(`${esc(r.commessa||'')} — ${esc(r.impianto||'')}`,`${esc(r.data||'')} • ${esc(r.operatore||'')} ${r.idSap?'• SAP '+esc(r.idSap):''}`,`<span class="badge">${esc(r.stato||'')}</span>`)).join(''):'<div class="empty">Nessuna riga importata.</div>';
 if($('cPending'))$('cPending').textContent=db.consuntivi.filter(x=>x.status==='Da verificare').length;
 if($('cApproved'))$('cApproved').textContent=db.consuntivi.filter(x=>x.status==='Approvato').length;
 if($('cPosted'))$('cPosted').textContent=db.consuntivi.filter(x=>x.status==='Contabilizzato').length;
 if($('consList')){let f=$('consFilter')?.value||'',q=norm($('consSearch')?.value||'');let rows=db.consuntivi.filter(x=>(!f||x.status===f)&&(!q||norm([x.commessa,x.codiceCommessa,x.impianto,x.idSap,x.operatore,x.lavorazione,x.note].join(' ')).includes(q)));$('consList').innerHTML=rows.length?rows.slice().reverse().map(c=>item(`${esc(c.commessa||'')} — ${esc(c.impianto||'')}`,`${esc(c.data||'')} • ${esc(c.operatore||'')} • ${esc(c.lavorazione||'')} ${c.ore?`• ${esc(c.ore)} h`:''}`,`<strong>${c.importo?euro(c.importo):''}</strong> <span class="badge">${esc(c.status)}</span>`,`<button class="mini" data-cons-approve="${c.id}">Approva</button><button class="mini" data-cons-post="${c.id}">Contabilizza</button>`)).join(''):'<div class="empty">Nessun consuntivo.</div>'}
 bindDynamic();updateBackupInfo();
}
setTimeout(async()=>{const stored=await readLargeEntries();if(stored.length&&stored.length>db.entries.length){db.entries=stored;try{refresh()}catch(error){console.warn('Aggiornamento prezziari grandi rinviato',error)}}},0);
