function rawRecordKey(r){return String(r?.sourcePath||`${r?.rootCollection||'unknown'}/${r?.id||''}`)}
function stableData(v){if(Array.isArray(v))return v.map(stableData);if(v&&typeof v==='object'){let o={};Object.keys(v).sort().forEach(k=>{if(k!=='syncedAt')o[k]=stableData(v[k])});return o}return v}
function mergeRawVcRecords(records){let map=new Map((db.vcRecords||[]).map(r=>[rawRecordKey(r),r])),created=0,updated=0,unchanged=0;(records||[]).forEach(r=>{let k=rawRecordKey(r);if(!k)return;let next={...r,sourcePath:k,syncedAt:new Date().toISOString()},old=map.get(k);if(!old){map.set(k,next);created++;return}if(JSON.stringify(stableData(old.data))!==JSON.stringify(stableData(next.data))){map.set(k,next);updated++}else unchanged++});db.vcRecords=[...map.values()];return{created,updated,unchanged,changed:created+updated}}
function firstVal(o,names){for(const n of names){let k=Object.keys(o||{}).find(x=>norm(x)===norm(n));if(k!=null&&o[k]!=null&&String(o[k]).trim()!=='')return o[k]}return''}
function vcNumber(v){if(typeof v==='number')return Number.isFinite(v)?v:0;let s=String(v??'').trim();if(!s)return 0;s=s.replace(/\s/g,'').replace(/\.(?=\d{3}(?:\D|$))/g,'').replace(',','.').replace(/[^0-9.-]/g,'');let n=Number(s);return Number.isFinite(n)?n:0}
function sourceCommessaPath(path){let p=String(path||'').split('/');let i=p.indexOf('commesse');return i>=0&&p[i+1]?`commesse/${p[i+1]}`:''}
function findJobForRecord(o){let cp=sourceCommessaPath(o.vcSourceId||o.sourcePath);if(cp){let j=db.jobs.find(x=>x.vcSourceId===cp);if(j)return j}return null}
function ensureClientFromCommessa(c,job){let name=String(job?.title||c.title||c.name||c.nome||c.commessa||'').trim();if(!name)return null;let client=db.clients.find(x=>x.vcCommessaSourceId===c.vcSourceId)||db.clients.find(x=>norm(x.name)===norm(name));if(!client){client={id:uid(),name,vat:'',address:'',city:String(c.comune||''),email:'',phone:'',priceListId:'',notes:'Cliente creato automaticamente dalla commessa Varga Cantieri.',vcCommessaSourceId:c.vcSourceId,source:'Varga Cantieri'};db.clients.push(client)}else{client.name=name;client.vcCommessaSourceId=c.vcSourceId}if(job)job.clientId=client.id;return client}
function isAccountingRow(o){return /\/lavorazioni\/[^/]+$/.test(String(o?.vcSourceId||o?.sourcePath||''))}
function accountingRowIsDone(o){return norm(String(o?.stato||''))==='fatto'}
function syncAccountingRow(o){if(!isAccountingRow(o)||!accountingRowIsDone(o))return{created:false,updated:false};let job=findJobForRecord(o);if(!job)return{created:false,updated:false};let sid=o.vcSourceId||o.sourcePath,existing=db.consuntivi.find(x=>x.sourceId===sid);let prezzoBase=vcNumber(o.prezzoBase),prezzoRibassato=vcNumber(o.prezzoRibassato),prezzo=prezzoRibassato||prezzoBase,quantita=vcNumber(o.quantita),totale=vcNumber(o.totale);if(!totale&&prezzo)totale=prezzo*(quantita||1);let base={sourceId:sid,sourceType:'commessa-lavorazione',commessa:job.title,codiceCommessa:job.code||'',clientId:job.clientId||'',impianto:String(o.denominazione||o.nome||''),idSap:String(o.idSap||''),comune:String(o.comune||''),data:String(o.dataEsecuzione||''),ora:String(o.oraEsecuzione||''),operatore:String(o.operatoreNome||''),lavorazione:String(o.tipologiaLavorazione||''),quantita:o.quantita??'',unita:String(o.unitaMisura||''),ore:o.ore??'',note:String(o.note||''),priceEntryId:'',priceCode:String(o.codiceVocePrezzo||''),prezzoBase,prezzoRibassato,prezzo,importo:totale,numeroProgressivoRiga:o.numeroProgressivoRiga??'',distretto:String(o.distretto||''),frequenzaAnnua:o.frequenzaAnnua??'',vcStatus:String(o.stato||''),updatedFromVargaAt:new Date().toISOString()};if(existing){if(existing.status!=='Contabilizzato'){Object.assign(existing,base);return{created:false,updated:true}}return{created:false,updated:false}}db.consuntivi.push({id:uid(),...base,status:'Da verificare',createdAt:new Date().toISOString()});return{created:true,updated:false}}
function mapSnapshotRecords(records,manifest={}){
 let groups={};(records||[]).forEach(r=>(groups[r.rootCollection]??=[]).push(r));const unpack=list=>(list||[]).map(r=>({...(r.data||{}),id:(r.data&&r.data.id)||r.id,vcSourceId:r.sourcePath,vcRootCollection:r.rootCollection}));let delta=mergeRawVcRecords(records),mapped=0,newCons=0,updatedCons=0,accountingRows=0;
 const mappings=[['impianti','vcImpianti'],['personale','vcUtenti'],['oreReports','vcOre'],['oreApprovalRequests','vcOre'],['squadre','vcSquadre'],['squadreCommesse','vcSquadre'],['squadreStorico','vcSquadre']];mappings.forEach(([root,key])=>{if(groups[root])mapped+=upsertBySource(db[key],unpack(groups[root]))});
 ['documents','posDocuments'].forEach(root=>{if(groups[root])mapped+=upsertBySource(db.documents,unpack(groups[root]).map(d=>({id:d.id||uid(),name:d.name||d.fileName||d.title||'Documento Varga Cantieri',category:d.category||d.type||root,driveUrl:d.driveUrl||d.url||d.webViewLink||'',notes:d.notes||'',clientId:'',jobId:'',addedBy:d.addedBy||d.userName||'Varga Cantieri',vcSourceId:d.vcSourceId,vcRootCollection:root}))) });Object.entries(groups).filter(([root])=>/segnal/i.test(root)).forEach(([,rows])=>{mapped+=upsertBySource(db.vcSegnalazioni,unpack(rows))});
 if(groups.commesse){let all=unpack(groups.commesse),rootCommesse=all.filter(x=>String(x.vcSourceId||'').split('/').length===2);mapped+=upsertBySource(db.vcCommesse,rootCommesse);rootCommesse.forEach(c=>{let existing=db.jobs.find(j=>j.vcSourceId===c.vcSourceId||j.sourceId===c.id),patch={title:c.title||c.name||c.nome||c.commessa||'Commessa Varga Cantieri',code:c.code||c.codice||c.codiceCommessa||'',clientId:existing?.clientId||'',site:c.site||c.cantiere||c.comune||'',start:c.start||c.dataInizio||'',end:c.end||c.dataFine||'',value:vcNumber(c.value||c.importo),status:c.status||c.stato||'Attiva',vcSourceId:c.vcSourceId,sourceId:c.id};if(existing)Object.assign(existing,patch);else{existing={id:uid(),...patch};db.jobs.push(existing)}ensureClientFromCommessa(c,existing)});all.filter(isAccountingRow).forEach(o=>{accountingRows++;let r=syncAccountingRow(o);if(r.created)newCons++;if(r.updated)updatedCons++})}
 db.meta.vcLastSync=new Date().toLocaleString('it-IT');db.meta.vcSnapshotId=manifest.snapshotId||'';db.meta.vcSnapshotGeneratedAt=manifest.generatedAt||'';db.meta.vcSnapshotCounts=manifest.counts||{};db.meta.vcAccountingRows=accountingRows;save();refreshVcCounts();return{...delta,mapped,newCons,updatedCons,accountingRows,records:(records||[]).length};
}
async function syncVargaFromCloud(options={}){if(!cloudFunctions||!cloudUser)throw Error('Accedi al Cloud con lo stesso progetto Firebase di Varga Cantieri.');let rebuild=cloudFunctions.httpsCallable('rebuildVargaGestionaleSnapshot'),manifestFn=cloudFunctions.httpsCallable('getVargaGestionaleSnapshotManifest'),chunkFn=cloudFunctions.httpsCallable('getVargaGestionaleSnapshotChunk'),manifest=null;if(options.rebuild===false){$('vcSyncInfo').textContent='Scarico la sincronizzazione programmata...';manifest=(await manifestFn({})).data}else{$('vcSyncInfo').textContent='Creo lo snapshot aggiornato di Varga Cantieri...';try{manifest=(await rebuild({})).data}catch(err){let code=String(err?.code||'');if(!/permission-denied/i.test(code))throw err;$('vcSyncInfo').textContent='Uso l’ultimo snapshot disponibile...';manifest=(await manifestFn({})).data}}if(!manifest||manifest.available===false||!manifest.snapshotId)throw Error('Nessuno snapshot Varga Cantieri disponibile.');let records=[];for(let i=0;i<Number(manifest.chunkCount||0);i++){$('vcSyncInfo').textContent=`Importazione Varga Cantieri: blocco ${i+1}/${manifest.chunkCount}...`;let chunk=(await chunkFn({snapshotId:manifest.snapshotId,index:i})).data;records.push(...(chunk.records||[]))}let result=mapSnapshotRecords(records,manifest);$('vcSyncInfo').textContent=`${result.records} controllati • ${result.created} nuovi • ${result.updated} modificati • ${result.unchanged} invariati • ${result.accountingRows} righe contabili • ${result.newCons} nuovi consuntivi.`;return result}

const AUTO_SYNC_SLOTS=['05:30','16:00'];let autoSyncRunning=false;
function dueAutoSyncSlot(){const now=new Date(),day=now.toLocaleDateString('sv-SE',{timeZone:'Europe/Rome'}),time=now.toLocaleTimeString('it-IT',{timeZone:'Europe/Rome',hour:'2-digit',minute:'2-digit',hour12:false});const due=AUTO_SYNC_SLOTS.filter(slot=>slot<=time).pop();return due?`${day} ${due}`:''}
async function runScheduledVargaSync(){const slot=dueAutoSyncSlot();if(!slot||autoSyncRunning||db.meta?.vargaAutoSyncSlot===slot||!cloudFunctions||!cloudUser)return;autoSyncRunning=true;try{await syncVargaFromCloud({rebuild:false});db.meta.vargaAutoSyncSlot=slot;db.meta.vargaAutoSyncAt=new Date().toISOString();save({skipCloud:true})}catch(error){console.warn('Sincronizzazione automatica Varga non riuscita',error)}finally{autoSyncRunning=false}}
setTimeout(runScheduledVargaSync,5000);setInterval(runScheduledVargaSync,60000);document.addEventListener('visibilitychange',()=>{if(!document.hidden)runScheduledVargaSync()});
if($('syncVcNow'))$('syncVcNow').onclick=async()=>{let url=$('vcEndpoint').value.trim();$('vcSyncInfo').textContent='Avvio sincronizzazione...';try{if(cloudFunctions&&cloudUser){await syncVargaFromCloud();return}if(!url)throw Error('Configura Firebase e accedi al Cloud, oppure inserisci un endpoint JSON di fallback.');let res=await fetch(url,{cache:'no-store'});if(!res.ok)throw Error(`HTTP ${res.status}`);let data=await res.json();if(Array.isArray(data)){let r=ingestVcRows(data);$('vcSyncInfo').textContent=`Sincronizzato Gestione Commesse: ${r.changed} variazioni, ${r.created} nuovi consuntivi.`}else{let c=importFullVarga(data);refreshVcCounts();$('vcSyncInfo').textContent=`Sincronizzazione completa: ${c.total} elementi nuovi/modificati.`}}catch(err){console.warn(err);$('vcSyncInfo').textContent='Errore sincronizzazione: '+err.message}};
if($('consFilter'))$('consFilter').onchange=refresh;if($('consSearch'))$('consSearch').oninput=refresh;
if($('exportConsCsv'))$('exportConsCsv').onclick=()=>{let rows=[['Cliente / Commessa','Codice commessa','Impianto','ID SAP','Comune','Data','Ora','Operatore','Lavorazione','Quantità','U.M.','Codice prezzo','Prezzo base','Prezzo ribassato','Importo','Stato'],...db.consuntivi.map(c=>[c.commessa,c.codiceCommessa,c.impianto,c.idSap,c.comune,c.data,c.ora,c.operatore,c.lavorazione,c.quantita,c.unita,c.priceCode,c.prezzoBase,c.prezzoRibassato,c.importo,c.status])],csv=rows.map(r=>r.map(v=>'"'+String(v??'').replace(/"/g,'""')+'"').join(';')).join('\n'),a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8'}));a.download=`Varga-Contabilita-${new Date().toISOString().slice(0,10)}.csv`;a.click();URL.revokeObjectURL(a.href)};
