// Varga Cantieri -> Gestione Commesse -> Consuntivi. La sorgente esterna viene letta solo su richiesta/importazione.
function vcArr(payload,...names){for(const n of names){if(Array.isArray(payload?.[n]))return payload[n]}return []}
function vcId(x,i,p='vc'){return String(x?.id??x?.ID??x?.uid??x?.uuid??x?.idSap??x?.['ID SAP']??`${p}-${i}`)}
function upsertBySource(target,rows,prefix){let changed=0;rows.forEach((raw,i)=>{let sourceId=vcId(raw,i,prefix),idx=target.findIndex(x=>String(x.sourceId||x.id)===sourceId),rec={...raw,sourceId,source:'Varga Cantieri',syncedAt:new Date().toISOString()};if(idx<0){target.push(rec);changed++}else if(JSON.stringify({...target[idx],syncedAt:null})!==JSON.stringify({...rec,syncedAt:null})){target[idx]={...target[idx],...rec};changed++}});return changed}
function importFullVarga(payload){if(!payload||typeof payload!=='object')throw Error('Pacchetto Varga Cantieri non valido.');let commesse=vcArr(payload,'commesse','projects','jobs'),impianti=vcArr(payload,'impianti','sites','plants'),squadre=vcArr(payload,'squadre','teams'),ore=vcArr(payload,'ore','hours','timbrature','attivita'),segn=vcArr(payload,'segnalazioni','reports','notes'),utenti=vcArr(payload,'utenti','users','personale','operators'),docs=vcArr(payload,'documenti','documents','files'),gest=vcArr(payload,'gestioneCommesse','cantieriRows','fatti','rows');let counts={commesse:upsertBySource(db.vcCommesse,commesse,'commessa'),impianti:upsertBySource(db.vcImpianti,impianti,'impianto'),squadre:upsertBySource(db.vcSquadre,squadre,'squadra'),ore:upsertBySource(db.vcOre,ore,'ore'),segnalazioni:upsertBySource(db.vcSegnalazioni,segn,'segn'),utenti:upsertBySource(db.vcUtenti,utenti,'utente'),documenti:0,gestione:0};
commesse.forEach((c,i)=>{let sid=vcId(c,i,'commessa'),j=db.jobs.find(x=>x.vcSourceId===sid);let title=c.name||c.nome||c.commessa||c.denominazione||`Commessa ${sid}`,code=c.code||c.codice||c.codiceCommessa||'';if(!j)db.jobs.push({id:uid(),vcSourceId:sid,title,code,clientId:'',site:c.site||c.cantiere||'',start:c.start||c.dataInizio||'',end:c.end||c.dataFine||'',status:c.status||c.stato||'Importata',value:Number(c.value||c.importo||0),notes:'Importata da Varga Cantieri'});else Object.assign(j,{title,code,status:c.status||c.stato||j.status,site:c.site||c.cantiere||j.site})});
docs.forEach((d,i)=>{let sid=vcId(d,i,'doc'),existing=db.documents.find(x=>x.vcSourceId===sid);let rec={id:existing?.id||uid(),vcSourceId:sid,name:d.name||d.nome||d.filename||`Documento ${sid}`,category:d.category||d.categoria||d.tipo||'Varga Cantieri',clientId:'',jobId:'',driveUrl:d.driveUrl||d.url||d.webViewLink||d.link||'',notes:d.notes||d.note||'',date:d.date||d.createdAt||new Date().toISOString(),addedBy:d.addedBy||d.operatore||'Varga Cantieri'};if(existing)Object.assign(existing,rec);else{db.documents.push(rec);counts.documenti++}});
if(gest.length){let r=ingestVcRows(gest);counts.gestione=r.changed}
counts.total=Object.values(counts).reduce((a,b)=>a+(Number(b)||0),0);db.meta.vcLastFullSync=new Date().toISOString();save();return counts}
function refreshVcCounts(){if($('vcCountCommesse'))$('vcCountCommesse').textContent=db.vcCommesse.length;if($('vcCountImpianti'))$('vcCountImpianti').textContent=db.vcImpianti.length;if($('vcCountOre'))$('vcCountOre').textContent=db.vcOre.length;if($('vcCountDocs'))$('vcCountDocs').textContent=db.documents.filter(d=>d.vcSourceId).length;if($('vcCountRecords'))$('vcCountRecords').textContent=db.vcRecords.length}

const vcCfg=S.get('vg_vcConfig',{});
function hashText(s){let h=2166136261;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return(h>>>0).toString(36)}
function vcVal(obj,names){for(const n of names){let k=Object.keys(obj).find(x=>norm(x)===norm(n)||norm(x).includes(norm(n)));if(k&&obj[k]!==undefined&&obj[k]!==null)return obj[k]}return''}
function normalizeVcRow(o,i=0){let id=String(vcVal(o,['ID univoco','ID','uuid','row id'])||'').trim(),updated=String(vcVal(o,['Ultimo aggiornamento','updatedAt','aggiornato il','timestamp'])||'').trim();let r={sourceId:id||`row-${i}-${hashText(JSON.stringify(o))}`,updatedAt:updated,commessa:String(vcVal(o,['Commessa','Nome commessa'])||''),codiceCommessa:String(vcVal(o,['Codice commessa','Codice'])||''),impianto:String(vcVal(o,['Impianto','Denominazione Impianto','Cantiere'])||''),idSap:String(vcVal(o,['ID SAP','SAP'])||''),comune:String(vcVal(o,['Comune','Comune ubicazione'])||''),data:String(vcVal(o,['Data','Data fatto'])||''),ora:String(vcVal(o,['Ora','Ora fatto'])||''),operatore:String(vcVal(o,['Operatore','Squadra','Utente'])||''),lavorazione:String(vcVal(o,['Lavorazione','Descrizione lavoro','Attività'])||''),quantita:vcVal(o,['Quantità','Qta','Qtà']),unita:String(vcVal(o,['U.M.','UM','Unità di misura'])||''),ore:vcVal(o,['Ore','Ore lavorate']),note:String(vcVal(o,['Note','Nota'])||''),stato:String(vcVal(o,['Stato','FATTO','Esito'])||'')};r.fingerprint=hashText([r.sourceId,r.updatedAt,r.commessa,r.impianto,r.data,r.ora,r.stato,r.lavorazione,r.quantita,r.ore,r.note].join('|'));return r}
function isFatto(r){let x=norm(r.stato);return x==='fatto'||x==='finito'||x==='terminato'||x.includes('fatto')||x.includes('complet')}
function matchPriceEntry(r){let text=norm(`${r.lavorazione} ${r.impianto}`);if(!text)return null;let toks=text.split(/\s+/).filter(x=>x.length>3),best=null,score=0;for(const e of db.entries){let d=norm(e.description),sc=toks.reduce((a,t)=>a+(d.includes(t)?1:0),0);if(sc>score){score=sc;best=e}}return score?best:null}
function ingestVcRows(rows){let changed=0,created=0;for(let i=0;i<rows.length;i++){let r=normalizeVcRow(rows[i],i),old=db.cantieriRows.find(x=>x.sourceId===r.sourceId);if(old&&old.fingerprint===r.fingerprint)continue;if(old)Object.assign(old,r);else db.cantieriRows.push(r);changed++;if(isFatto(r)){let c=db.consuntivi.find(x=>x.sourceId===r.sourceId),pe=matchPriceEntry(r),base={sourceId:r.sourceId,sourceFingerprint:r.fingerprint,commessa:r.commessa,codiceCommessa:r.codiceCommessa,impianto:r.impianto,idSap:r.idSap,comune:r.comune,data:r.data,ora:r.ora,operatore:r.operatore,lavorazione:r.lavorazione,quantita:r.quantita||1,unita:r.unita||pe?.unit||'',ore:r.ore,note:r.note,priceEntryId:pe?.id||'',priceCode:pe?.code||'',prezzo:pe?.price||0,importo:pe?Number(r.quantita||1)*Number(pe.price||0):0};if(c){if(c.status!=='Contabilizzato')Object.assign(c,base,{status:c.status||'Da verificare'})}else{db.consuntivi.push({id:uid(),...base,status:'Da verificare',createdAt:new Date().toISOString()});created++}}}db.meta.vcLastSync=new Date().toLocaleString('it-IT');save();if($('vcSyncInfo'))$('vcSyncInfo').textContent=`Sincronizzazione completata: ${changed} righe nuove/modificate, ${created} nuovi consuntivi.`;return{changed,created}}
function rowsFromSheetAoA(aoa){if(!aoa?.length)return[];let headers=aoa[0].map(x=>String(x||''));return aoa.slice(1).filter(r=>r.some(v=>String(v??'').trim())).map(r=>Object.fromEntries(headers.map((h,i)=>[h,r[i]])))}
if($('vcEndpoint'))$('vcEndpoint').value=vcCfg.endpoint||'';
if($('saveVcEndpoint'))$('saveVcEndpoint').onclick=()=>{vcCfg.endpoint=$('vcEndpoint').value.trim();S.set('vg_vcConfig',vcCfg);$('vcSyncInfo').textContent='URL salvato su questo PC.'};
if($('vcFile'))$('vcFile').onchange=async e=>{let f=e.target.files?.[0];if(!f)return;try{let rows;if(f.name.toLowerCase().endsWith('.csv')){let txt=await f.text(),lines=txt.split(/\r?\n/).filter(Boolean),sep=(lines[0].split(';').length>lines[0].split(',').length)?';':',',aoa=lines.map(l=>l.split(sep));rows=rowsFromSheetAoA(aoa)}else{if(typeof XLSX==='undefined')throw Error('Libreria Excel non disponibile.');let wb=XLSX.read(await f.arrayBuffer(),{type:'array'}),ws=wb.Sheets[wb.SheetNames[0]],aoa=XLSX.utils.sheet_to_json(ws,{header:1,defval:''});rows=rowsFromSheetAoA(aoa)}let r=ingestVcRows(rows);alert(`Importazione completata. ${r.changed} righe nuove/modificate.`)}catch(err){console.warn(err);alert('Importazione Gestione Commesse non riuscita: '+err.message)}};
