// Gestione semplice degli utenti autorizzati per il workspace condiviso.
(function(){
  'use strict';
  let currentRole='',membersUnsub=null;
  const $=id=>document.getElementById(id);
  const email=v=>String(v||'').trim().toLowerCase();
  const labels={admin:'Amministratore',ufficio:'Ufficio',operatore:'Operatore'};
  function workspaceId(){return String($('workspaceId')?.value||cloudCfg.workspaceId||'varga-azienda').trim().replace(/[^a-zA-Z0-9_-]/g,'_')}
  function membersRef(){return cloudStore.collection('appConfig').doc('vargaGestionaleWorkspace_'+workspaceId()+'_members')}
  function installUi(){const cards=$('cloud')?.querySelector('.cards');if(cards&&!$('cloudRole'))cards.insertAdjacentHTML('beforeend','<div class="card"><span>Ruolo</span><strong class="small" id="cloudRole">-</strong></div>');const sync=$('cloudInfo')?.closest('.panel');if(sync&&!$('cloudMembersPanel'))sync.insertAdjacentHTML('beforebegin','<div class="panel" id="cloudMembersPanel"><h2>Utenti autorizzati</h2><p class="muted">Il primo utente diventa Amministratore. Solo l’Amministratore può autorizzare altre email.</p><div class="grid2"><label>Email da autorizzare<input id="memberEmail" type="email" placeholder="nome@gmail.com"></label><label>Ruolo<select id="memberRole"><option value="ufficio">Ufficio</option><option value="operatore">Operatore</option><option value="admin">Amministratore</option></select></label></div><div class="actions left"><button id="addCloudMember" class="primary">AUTORIZZA UTENTE</button></div><div id="cloudMembersList" class="list" style="margin-top:12px"><div class="empty">Accedi per visualizzare gli utenti.</div></div></div>');if($('addCloudMember'))$('addCloudMember').onclick=addMember}
  function render(data={}){installUi();if($('cloudRole'))$('cloudRole').textContent=labels[currentRole]||'Non autorizzato';const list=$('cloudMembersList'),invites=data.invites||{};if(list)list.innerHTML=Object.keys(invites).sort().map(mail=>`<div class="item"><div class="item-main"><div class="item-title">${typeof esc==='function'?esc(mail):mail}</div><div class="item-sub">${labels[invites[mail]]||invites[mail]}</div></div></div>`).join('')||'<div class="empty">Nessun altro utente autorizzato.</div>';const admin=currentRole==='admin';if($('memberEmail'))$('memberEmail').disabled=!admin;if($('memberRole'))$('memberRole').disabled=!admin;if($('addCloudMember'))$('addCloudMember').disabled=!admin}
  async function addMember(){if(currentRole!=='admin')return alert('Solo un Amministratore può autorizzare utenti.');const mail=email($('memberEmail')?.value),role=$('memberRole')?.value||'operatore';if(!/^\S+@\S+\.\S+$/.test(mail))return alert('Inserisci un indirizzo email valido.');await membersRef().set({workspaceId:workspaceId(),invites:{[mail]:role},updatedAt:firebase.firestore.FieldValue.serverTimestamp(),updatedBy:cloudUser.uid},{merge:true});$('memberEmail').value=''}
  window.authorizeCloudUser=async function(user){installUi();const ref=membersRef(),mail=email(user.email);const role=await cloudStore.runTransaction(async tx=>{const snap=await tx.get(ref);if(!snap.exists){tx.set(ref,{workspaceId:workspaceId(),ownerUid:user.uid,ownerEmail:mail,invites:{[mail]:'admin'},createdAt:firebase.firestore.FieldValue.serverTimestamp()});return'admin'}const data=snap.data()||{},found=data.ownerUid===user.uid?'admin':(data.invites||{})[mail]||'';if(found)tx.set(ref,{activeUsers:{[user.uid]:{email:mail,name:user.displayName||mail,role:found,lastLoginAt:new Date().toISOString()}}},{merge:true});return found});currentRole=role;window.cloudUserRole=role;render((await ref.get()).data()||{});if(membersUnsub)membersUnsub();membersUnsub=ref.onSnapshot(s=>render(s.data()||{}));return Boolean(role)};
  window.cloudUserSignedOut=function(){currentRole='';window.cloudUserRole='';if(membersUnsub){membersUnsub();membersUnsub=null}render({})};
  installUi();
})();
