/* Gestione cartelle Google Drive dentro Varga Gestionale, tramite ponte Apps Script. */
(function(){
'use strict';
const states=new WeakMap();
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const jobPayload=job=>({id:job?.id||'',title:job?.title||'Commessa',code:job?.code||''});
const size=n=>{n=Number(n||0);if(n<1024)return n+' B';if(n<1048576)return(n/1024).toFixed(1)+' KB';return(n/1048576).toFixed(1)+' MB'};
function style(){if(document.getElementById('vgDriveStyle'))return;const s=document.createElement('style');s.id='vgDriveStyle';s.textContent=`.vg-drive-tools{display:flex;gap:8px;flex-wrap:wrap;margin:12px 0}.vg-drive-tools input[type=search]{flex:1;min-width:220px}.vg-drive-path{display:flex;gap:6px;align-items:center;flex-wrap:wrap;padding:10px 12px;background:#f5f8f6;border-radius:10px}.vg-drive-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(230px,1fr));gap:10px;margin-top:12px}.vg-drive-item{border:1px solid #dce5df;border-radius:12px;padding:12px;background:#fff;display:grid;grid-template-columns:auto minmax(0,1fr);gap:10px;align-items:start}.vg-drive-icon{font-size:25px}.vg-drive-name{font-weight:800;overflow-wrap:anywhere}.vg-drive-meta{font-size:12px;color:#667085;margin-top:4px}.vg-drive-actions{grid-column:1/-1;display:flex;gap:6px;flex-wrap:wrap}.vg-drive-actions button{font-size:11px;padding:6px 8px}.vg-drive-modal{position:fixed;inset:0;background:rgba(5,20,14,.72);z-index:100000;display:flex;align-items:center;justify-content:center;padding:18px}.vg-drive-modal-card{background:#fff;border-radius:14px;width:min(1100px,96vw);height:min(820px,94vh);display:flex;flex-direction:column;overflow:hidden}.vg-drive-modal-head{display:flex;justify-content:space-between;gap:10px;align-items:center;padding:12px 15px;border-bottom:1px solid #ddd}.vg-drive-modal-body{flex:1;min-height:0;background:#eef2ef;display:flex;align-items:center;justify-content:center}.vg-drive-modal-body iframe,.vg-drive-modal-body img{width:100%;height:100%;border:0;object-fit:contain}.vg-drive-empty{padding:24px;text-align:center;color:#667085;border:1px dashed #ccd4dd;border-radius:10px;margin-top:12px}`;document.head.appendChild(s)}
async function call(action,state,extra={}){if(typeof window.VargaMailBridgeCall!=='function')throw Error('Ponte Google Apps Script non configurato.');if(typeof cloudUser==='undefined'||!cloudUser)throw Error('Accedi prima a Varga Gestionale.');return window.VargaMailBridgeCall(action,{job:jobPayload(state.job),...extra})}
function render(host){const s=states.get(host);if(!s)return;host.innerHTML=`<div class="vg-drive-path"><button class="ghost" data-drive-back ${s.history.length?'':'disabled'}>← INDIETRO</button><strong>📁 ${esc(s.folderName||s.job.title)}</strong><span class="muted">${s.loading?'Caricamento…':''}</span></div><div class="vg-drive-tools"><input type="search" data-drive-search placeholder="Cerca file o cartella…" value="${esc(s.query)}"><button class="ghost" data-drive-new>+ CARTELLA</button><label class="primary" style="cursor:pointer;padding:9px 12px;border-radius:9px">CARICA FILE<input type="file" data-drive-upload hidden multiple></label><button class="ghost" data-drive-refresh>AGGIORNA</button></div><div data-drive-list></div>`;bind(host);drawList(host)}
function drawList(host){const s=states.get(host),target=host.querySelector('[data-drive-list]');if(!s||!target)return;const q=s.query.toLowerCase(),items=[...(s.data?.folders||[]),...(s.data?.files||[])].filter(x=>!q||x.name.toLowerCase().includes(q));if(s.error){target.innerHTML=`<div class="vg-drive-empty">${esc(s.error)}</div>`;return}if(s.loading){target.innerHTML='<div class="vg-drive-empty">Caricamento archivio Drive…</div>';return}target.innerHTML=items.length?`<div class="vg-drive-grid">${items.map(x=>`<div class="vg-drive-item"><div class="vg-drive-icon">${x.kind==='folder'?'📁':'📄'}</div><div><div class="vg-drive-name">${esc(x.name)}</div><div class="vg-drive-meta">${x.kind==='folder'?'Cartella':`${esc(x.mimeType||'File')} · ${size(x.size)}`}</div></div><div class="vg-drive-actions">${x.kind==='folder'?`<button class="primary" data-drive-open="${esc(x.id)}">APRI</button>`:`<button class="primary" data-drive-preview="${esc(x.id)}">VISUALIZZA</button><button class="ghost" data-drive-download="${esc(x.id)}">SCARICA</button>`}<button class="ghost" data-drive-rename="${esc(x.id)}" data-kind="${x.kind}" data-name="${esc(x.name)}">RINOMINA</button><button class="danger" data-drive-delete="${esc(x.id)}" data-kind="${x.kind}">ELIMINA</button></div></div>`).join('')}</div>`:'<div class="vg-drive-empty">Questa cartella è vuota.</div>';bindItems(host)}
async function load(host,ensure=false){const s=states.get(host);s.loading=true;s.error='';render(host);try{s.data=await call(ensure?'driveEnsureJob':'driveList',s,{folderId:s.folderId||''});s.folderId=s.data.folderId;s.folderName=s.data.folderName}catch(e){if(!ensure&&/Cartella fuori dalla commessa/i.test(e.message||'')){s.folderId='';s.folderName=s.job.title;s.history=[];try{s.data=await call('driveEnsureJob',s,{folderId:''});s.folderId=s.data.folderId;s.folderName=s.data.folderName}catch(retry){s.error=retry.message||String(retry)}}else s.error=e.message||String(e)}finally{s.loading=false;render(host)}}
function bind(host){const s=states.get(host);host.querySelector('[data-drive-search]').oninput=e=>{s.query=e.target.value;drawList(host)};host.querySelector('[data-drive-refresh]').onclick=()=>load(host);host.querySelector('[data-drive-back]').onclick=()=>{const prev=s.history.pop();if(prev){s.folderId=prev.id;s.folderName=prev.name;load(host)}};host.querySelector('[data-drive-new]').onclick=async()=>{const name=prompt('Nome della nuova cartella:');if(!name)return;try{await call('driveCreateFolder',s,{folderId:s.folderId,name});await load(host)}catch(e){alert(e.message||e)}};host.querySelector('[data-drive-upload]').onchange=async e=>{for(const file of [...e.target.files]){if(file.size>8*1024*1024){alert(`${file.name}: supera 8 MB.`);continue}try{const base64=await fileBase64(file);await call('driveUpload',s,{folderId:s.folderId,name:file.name,mimeType:file.type||'application/octet-stream',base64})}catch(err){alert(`${file.name}: ${err.message||err}`)}}e.target.value='';await load(host)}}
function bindItems(host){const s=states.get(host);host.querySelectorAll('[data-drive-open]').forEach(b=>b.onclick=()=>{s.history.push({id:s.folderId,name:s.folderName});s.folderId=b.dataset.driveOpen;s.folderName=b.closest('.vg-drive-item').querySelector('.vg-drive-name').textContent;load(host)});host.querySelectorAll('[data-drive-preview]').forEach(b=>b.onclick=()=>getFile(host,b.dataset.drivePreview,true));host.querySelectorAll('[data-drive-download]').forEach(b=>b.onclick=()=>getFile(host,b.dataset.driveDownload,false));host.querySelectorAll('[data-drive-rename]').forEach(b=>b.onclick=async()=>{const name=prompt('Nuovo nome:',b.dataset.name);if(!name||name===b.dataset.name)return;try{await call('driveRename',s,{itemId:b.dataset.driveRename,kind:b.dataset.kind,name});await load(host)}catch(e){alert(e.message||e)}});host.querySelectorAll('[data-drive-delete]').forEach(b=>b.onclick=async()=>{if(!confirm('Spostare questo elemento nel cestino?'))return;try{await call('driveTrash',s,{itemId:b.dataset.driveDelete,kind:b.dataset.kind});await load(host)}catch(e){alert(e.message||e)}})}
function fileBase64(file){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result).split(',')[1]||'');r.onerror=()=>reject(r.error);r.readAsDataURL(file)})}
function bytes(base64){const raw=atob(base64),out=new Uint8Array(raw.length);for(let i=0;i<raw.length;i++)out[i]=raw.charCodeAt(i);return out}
async function getFile(host,id,preview){const s=states.get(host);try{const r=await call('driveGetFile',s,{fileId:id}),blob=new Blob([bytes(r.base64)],{type:r.mimeType||'application/octet-stream'}),url=URL.createObjectURL(blob);if(!preview){const a=document.createElement('a');a.href=url;a.download=r.name||'documento';a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);return}showPreview(r,url)}catch(e){alert(e.message||e)}}
function showPreview(file,url){const supported=/^(image\/|application\/pdf|text\/)/.test(file.mimeType||'');if(!supported){const a=document.createElement('a');a.href=url;a.download=file.name;a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);return alert('Questo formato viene scaricato perché non dispone di anteprima interna.')}const modal=document.createElement('div');modal.className='vg-drive-modal';modal.innerHTML=`<div class="vg-drive-modal-card"><div class="vg-drive-modal-head"><strong>${esc(file.name)}</strong><button class="ghost" data-close>CHIUDI</button></div><div class="vg-drive-modal-body">${String(file.mimeType).startsWith('image/')?`<img src="${url}" alt="${esc(file.name)}">`:`<iframe src="${url}" title="${esc(file.name)}"></iframe>`}</div></div>`;const close=()=>{URL.revokeObjectURL(url);modal.remove()};modal.querySelector('[data-close]').onclick=close;modal.onclick=e=>{if(e.target===modal)close()};document.body.appendChild(modal)}
function mount(host,job){style();if(!host||!job)return;if(states.get(host)?.job?.id===job.id)return;states.set(host,{job,folderId:'',folderName:job.title,history:[],query:'',data:{folders:[],files:[]},loading:false,error:''});load(host,true)}
window.VargaDriveManager={mount};
})();
