/* Accesso Varga Gestionale sempre disponibile nella barra laterale. */
(function(){
'use strict';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function style(){if(document.getElementById('vgSidebarAuthStyle'))return;const s=document.createElement('style');s.id='vgSidebarAuthStyle';s.textContent=`.sidebar{padding-bottom:105px!important}.vg-sidebar-auth{position:fixed;left:14px;bottom:12px;width:217px;padding-top:10px;border-top:1px solid rgba(255,255,255,.14);z-index:30}.vg-sidebar-login{width:100%;border:1px solid rgba(255,255,255,.28);background:#1b6146;color:#fff;padding:10px;border-radius:10px;font-weight:900}.vg-sidebar-user{display:grid;grid-template-columns:34px minmax(0,1fr) auto;align-items:center;gap:8px;color:#fff}.vg-sidebar-avatar{width:34px;height:34px;border-radius:50%;display:grid;place-items:center;background:#84d4a8;color:#123b2c;font-weight:900}.vg-sidebar-user-name{font-weight:800;font-size:12px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.vg-sidebar-user-role{font-size:10px;color:#bcd4c7;margin-top:2px}.vg-sidebar-exit{border:0;background:transparent;color:#fff;padding:6px;font-size:18px}.vg-login-modal{position:fixed;inset:0;background:rgba(4,18,12,.72);z-index:100001;display:grid;place-items:center;padding:18px}.vg-login-card{width:min(460px,96vw);background:#fff;border-radius:16px;padding:20px;box-shadow:0 18px 50px rgba(0,0,0,.3)}.vg-login-card h2{margin:0}.vg-login-card .vg-login-close{float:right;border:0;background:#eef4f0;padding:7px 10px}.vg-login-fields{display:grid;gap:10px;margin:16px 0}.vg-login-actions{display:grid;gap:8px}.vg-login-actions button{width:100%}@media(max-width:850px){.vg-sidebar-auth{width:152px;left:14px}.vg-sidebar-user{grid-template-columns:30px minmax(0,1fr) auto}.vg-sidebar-avatar{width:30px;height:30px}}`;document.head.appendChild(s)}
function labelRole(){return({admin:'Amministratore',ufficio:'Ufficio',operatore:'Operatore'})[window.cloudUserRole]||'Utente autorizzato'}
function render(){const host=document.getElementById('vgSidebarAuth');if(!host)return;const user=typeof cloudUser!=='undefined'?cloudUser:null;if(!user){host.innerHTML='<button class="vg-sidebar-login" data-login>ACCEDI / REGISTRATI</button>';host.querySelector('[data-login]').onclick=open;return}const name=user.displayName||user.email||'Utente',initial=String(name).trim().charAt(0).toUpperCase()||'U';host.innerHTML=`<div class="vg-sidebar-user"><div class="vg-sidebar-avatar">${esc(initial)}</div><div role="button" data-account><div class="vg-sidebar-user-name">${esc(name)}</div><div class="vg-sidebar-user-role">${esc(labelRole())}</div></div><button class="vg-sidebar-exit" title="Esci" data-exit>↪</button></div>`;host.querySelector('[data-account]').onclick=()=>typeof nav==='function'&&nav('cloud');host.querySelector('[data-exit]').onclick=()=>{if(typeof cloudAuth!=='undefined'&&cloudAuth)cloudAuth.signOut();else document.getElementById('logoutCloud')?.click()}}
function open(){document.getElementById('vgLoginModal')?.remove();const m=document.createElement('div');m.id='vgLoginModal';m.className='vg-login-modal';m.innerHTML=`<div class="vg-login-card"><button class="vg-login-close" data-close>✕</button><h2>Accesso Varga Gestionale</h2><p class="muted">Accedi con un account autorizzato.</p><div class="vg-login-actions"><button class="primary" data-google>ACCEDI CON GOOGLE</button></div><div class="vg-login-fields"><input type="email" data-email placeholder="Email"><input type="password" data-password placeholder="Password"></div><div class="vg-login-actions"><button class="ghost" data-email-login>ACCEDI CON EMAIL</button><button class="ghost" data-register>CREA UTENTE</button></div></div>`;const close=()=>m.remove();m.querySelector('[data-close]').onclick=close;m.onclick=e=>{if(e.target===m)close()};m.querySelector('[data-google]').onclick=()=>{document.getElementById('loginGoogleCloud')?.click();close()};const copy=()=>{const email=document.getElementById('authEmail'),password=document.getElementById('authPassword');if(email)email.value=m.querySelector('[data-email]').value.trim();if(password)password.value=m.querySelector('[data-password]').value};m.querySelector('[data-email-login]').onclick=()=>{copy();document.getElementById('loginCloud')?.click();close()};m.querySelector('[data-register]').onclick=()=>{copy();document.getElementById('registerCloud')?.click();close()};document.body.appendChild(m)}
function install(){style();const side=document.querySelector('.sidebar');if(!side)return;if(!document.getElementById('vgSidebarAuth')){const host=document.createElement('div');host.id='vgSidebarAuth';host.className='vg-sidebar-auth';side.appendChild(host)}render()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install);else install();setInterval(render,500);window.addEventListener('storage',render);
})();
