(function(){
'use strict';
const byId=id=>document.getElementById(id), html=value=>typeof esc==='function'?esc(String(value??'')):String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const statuses=['Da fare','In corso','Completata'];let editingId='';
const all=()=>Array.isArray(db.deadlines)?db.deadlines:[];
const job=id=>(db.jobs||[]).find(x=>String(x.id)===String(id));
const jobName=id=>{const j=job(id);return j?[j.code,j.title].filter(Boolean).join(' — '):''};
const status=d=>d.done?'Completata':(statuses.includes(d.status)?d.status:'Da fare');
const overdue=d=>Boolean(d.date&&!d.done&&d.date<new Date().toISOString().slice(0,10));
const calendarReady=()=>{let local={};try{local=JSON.parse(localStorage.getItem('vg_mapMailBridge')||'{}')||{}}catch(_){}return typeof window.VargaMailBridgeCall==='function'&&Boolean((db.company?.driveBridge?.url)||local.url)};
function bridge(action,extra){if(typeof window.VargaMailBridgeCall!=='function')throw Error('Configura prima il ponte Google in Dati azienda.');return window.VargaMailBridgeCall(action,extra)}
function fillJobs(){const opts='<option value="">Nessuna commessa</option>'+(db.jobs||[]).slice().sort((a,b)=>String(a.title).localeCompare(String(b.title))).map(j=>`<option value="${html(j.id)}">${html(jobName(j.id))}</option>`).join('');if(byId('dJob')){const v=byId('dJob').value;byId('dJob').innerHTML=opts;byId('dJob').value=v}if(byId('taskJobFilter')){const v=byId('taskJobFilter').value;byId('taskJobFilter').innerHTML='<option value="">Tutte le commesse</option>'+opts.replace('<option value="">Nessuna commessa</option>','');byId('taskJobFilter').value=v}}
function calendarText(d){if(!d.date||d.calendarEnabled===false)return'';if(d.calendarEventId)return'<span class="task-chip task-calendar-ok">CALENDAR ✓</span>';if(d.calendarError)return'<span class="task-chip task-calendar-warn">CALENDAR DA SINCRONIZZARE</span>';return'<span class="task-chip">CALENDAR</span>'}
function card(d){const s=status(d),p=String(d.priority||'Normale').toLowerCase(),j=jobName(d.jobId),dateText=d.date?new Date(d.date+'T12:00:00').toLocaleDateString('it-IT')+(d.time?' • '+d.time:''):'Senza scadenza';return `<article class="task-card priority-${html(p)} ${overdue(d)?'is-overdue':''}" draggable="true" data-task-id="${html(d.id)}"><div class="task-card-head"><div class="task-card-title">${html(d.title)}</div><button class="task-card-menu" data-task-edit="${html(d.id)}" title="Modifica">✎</button></div><div class="task-card-meta"><span class="task-chip ${overdue(d)?'overdue':''}">${overdue(d)?'SCADUTA • ':''}${html(dateText)}</span><span class="task-chip">${html(d.priority||'Normale')}</span>${d.type?`<span class="task-chip">${html(d.type)}</span>`:''}${calendarText(d)}</div>${j?`<div class="task-card-notes"><strong>${html(j)}</strong></div>`:''}${d.assignee?`<div class="task-card-notes">Responsabile: ${html(d.assignee)}</div>`:''}${d.notes?`<div class="task-card-notes">${html(d.notes)}</div>`:''}<div class="task-card-actions">${s==='Da fare'?`<button class="mini primary" data-task-move="${html(d.id)}" data-next="In corso">INIZIA</button>`:''}${s==='In corso'?`<button class="mini primary" data-task-move="${html(d.id)}" data-next="Completata">COMPLETA</button>`:''}${s==='Completata'?`<button class="mini" data-task-move="${html(d.id)}" data-next="Da fare">RIAPRI</button>`:''}<button class="mini danger" data-task-delete="${html(d.id)}">ELIMINA</button></div></article>`}
function filtered(){const q=String(byId('taskSearch')?.value||'').trim().toLowerCase(),jf=byId('taskJobFilter')?.value||'',pf=byId('taskPriorityFilter')?.value||'',hide=byId('taskHideDone')?.checked;return all().filter(d=>(!q||[d.title,d.notes,d.assignee,d.type,jobName(d.jobId)].join(' ').toLowerCase().includes(q))&&(!jf||d.jobId===jf)&&(!pf||(d.priority||'Normale')===pf)&&(!hide||status(d)!=='Completata')).sort((a,b)=>(a.date||'9999-12-31').localeCompare(b.date||'9999-12-31')||String(a.title).localeCompare(String(b.title)))}
function render(){if(!byId('taskBoard'))return;fillJobs();const rows=filtered();[['Da fare','taskTodo','taskCountTodo'],['In corso','taskDoing','taskCountDoing'],['Completata','taskDone','taskCountDone']].forEach(([s,listId,countId])=>{const part=rows.filter(x=>status(x)===s);byId(countId).textContent=part.length;byId(listId).innerHTML=part.map(card).join('')||'<div class="task-empty">Nessuna attività</div>'});bindCards();const info=byId('taskCalendarInfo');if(info)info.textContent=calendarReady()?'Google Calendar pronto: le attività con scadenza vengono sincronizzate automaticamente.':'Per la creazione automatica su Google Calendar, configura il ponte Google in Dati azienda.'}
function reset(){editingId='';['dTitle','dDate','dNotes','dAssignee'].forEach(id=>{if(byId(id))byId(id).value=''});byId('dTime').value='09:00';byId('dType').value='Attività';byId('dPriority').value='Normale';byId('dJob').value='';byId('dCalendar').checked=true;byId('addDeadline').textContent='SALVA ATTIVITÀ';byId('cancelTaskEdit').hidden=true}
function readForm(){return{title:byId('dTitle').value.trim(),date:byId('dDate').value,time:byId('dTime').value,type:byId('dType').value,priority:byId('dPriority').value,assignee:byId('dAssignee').value.trim(),jobId:byId('dJob').value,notes:byId('dNotes').value.trim(),calendarEnabled:byId('dCalendar').checked}}
async function syncCalendar(d,remove=false){if(!d.calendarEnabled&&!d.calendarEventId)return;if(!calendarReady()){d.calendarError='Ponte Google non configurato';return}try{if(remove||d.done||!d.date){if(d.calendarEventId)await bridge('calendarDelete',{calendarEventId:d.calendarEventId});d.calendarEventId='';d.calendarUrl=''}else{const out=await bridge('calendarUpsert',{task:{...d,jobName:jobName(d.jobId),reminderMinutes:60}});d.calendarEventId=out.eventId||d.calendarEventId||'';d.calendarUrl=out.eventUrl||''}d.calendarError='';d.calendarSyncedAt=new Date().toISOString()}catch(e){d.calendarError=String(e?.message||e);console.warn('Sincronizzazione Calendar non riuscita',e)}S.set('vg_deadlines',db.deadlines);if(typeof queueCloudPush==='function')queueCloudPush();render()}
async function store(){const v=readForm();if(!v.title)return alert('Scrivi cosa bisogna fare.');if(v.calendarEnabled&&!v.date)return alert('Per creare il promemoria su Google Calendar devi scegliere una scadenza.');let d=editingId?all().find(x=>x.id===editingId):null;if(d)Object.assign(d,v,{updatedAt:new Date().toISOString()});else{d={id:uid(),...v,status:'Da fare',done:false,createdAt:new Date().toISOString(),createdBy:typeof cloudDisplayName==='function'?cloudDisplayName():''};db.deadlines.push(d)}save();reset();await syncCalendar(d,false)}
function edit(id){const d=all().find(x=>x.id===id);if(!d)return;editingId=id;byId('dTitle').value=d.title||'';byId('dDate').value=d.date||'';byId('dTime').value=d.time||'09:00';byId('dType').value=[...byId('dType').options].some(o=>o.value===d.type)?d.type:'Generale';byId('dPriority').value=d.priority||'Normale';byId('dAssignee').value=d.assignee||'';byId('dJob').value=d.jobId||'';byId('dNotes').value=d.notes||'';byId('dCalendar').checked=d.calendarEnabled!==false;byId('addDeadline').textContent='AGGIORNA ATTIVITÀ';byId('cancelTaskEdit').hidden=false;byId('taskComposer').scrollIntoView({behavior:'smooth',block:'start'});byId('dTitle').focus()}
async function move(id,next){const d=all().find(x=>x.id===id);if(!d)return;d.status=next;d.done=next==='Completata';d.completedAt=d.done?new Date().toISOString():'';d.updatedAt=new Date().toISOString();save();await syncCalendar(d,d.done)}
async function remove(id){const d=all().find(x=>x.id===id);if(!d||!confirm('Eliminare questa attività?'))return;if(d.calendarEventId)await syncCalendar(d,true);db.deadlines=db.deadlines.filter(x=>x.id!==id);save();render()}
function bindCards(){document.querySelectorAll('[data-task-edit]').forEach(b=>b.onclick=()=>edit(b.dataset.taskEdit));document.querySelectorAll('[data-task-move]').forEach(b=>b.onclick=()=>move(b.dataset.taskMove,b.dataset.next));document.querySelectorAll('[data-task-calendar]').forEach(b=>b.onclick=()=>{const d=all().find(x=>x.id===b.dataset.taskCalendar);if(d)syncCalendar(d,false)});document.querySelectorAll('[data-task-delete]').forEach(b=>b.onclick=()=>remove(b.dataset.taskDelete));document.querySelectorAll('.task-card').forEach(c=>c.ondragstart=e=>e.dataTransfer.setData('text/plain',c.dataset.taskId))}
function install(){if(!byId('taskBoard'))return;const oldRefresh=window.refresh;window.refresh=function(){oldRefresh.apply(this,arguments);render()};byId('addDeadline').onclick=store;byId('cancelTaskEdit').onclick=reset;byId('openTaskComposer').onclick=()=>{reset();byId('taskComposer').scrollIntoView({behavior:'smooth'});byId('dTitle').focus()};['taskSearch','taskJobFilter','taskPriorityFilter','taskHideDone'].forEach(id=>byId(id).addEventListener(id==='taskSearch'?'input':'change',render));document.querySelectorAll('[data-task-status]').forEach(col=>{col.ondragover=e=>{e.preventDefault();col.classList.add('drag-over')};col.ondragleave=()=>col.classList.remove('drag-over');col.ondrop=e=>{e.preventDefault();col.classList.remove('drag-over');move(e.dataTransfer.getData('text/plain'),col.dataset.taskStatus)}});render()}
install();window.renderTaskBoard=render;
})();
