/* Ore lavorate per commessa + storico squadre, usando vcRecords + vcOre + vcSquadre. */
(function(){
'use strict';
const c=v=>String(v??'').trim();
const n=v=>c(v).toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'');
const e=v=>String(v??'').replace(/[&<>"']/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[x]));
const num=v=>{if(typeof v==='number')return Number.isFinite(v)?v:0;let s=c(v).replace(/\s/g,'');if(!s)return 0;if(s.includes(',')&&s.includes('.'))s=s.lastIndexOf(',')>s.lastIndexOf('.')?s.replace(/\./g,'').replace(',','.'):s.replace(/,/g,'');else s=s.replace(',','.');return Number(s.replace(/[^0-9.-]/g,''))||0};
const first=(o,names)=>{for(const wanted of names){const k=Object.keys(o||{}).find(x=>n(x)===n(wanted));if(k!=null&&o[k]!=null&&c(o[k])!=='')return o[k]}return''};
const asRecord=(o,kind)=>({sourcePath:c(o?.vcSourceId||o?.sourcePath||`${kind}/${o?.id||''}`),rootCollection:c(o?.vcRootCollection||o?.rootCollection||kind),data:o?.data&&typeof o.data==='object'?o.data:o});
function uniqueRecords(arr){const m=new Map();arr.forEach(r=>{const k=c(r.sourcePath)||JSON.stringify(r.data||{});if(k&&!m.has(k))m.set(k,r)});return [...m.values()]}
function hoursSources(){return uniqueRecords([...(db.vcRecords||[]),...(db.vcOre||[]).map(o=>asRecord(o,'ore'))])}
function squadSources(){return uniqueRecords([...(db.vcRecords||[]),...(db.vcSquadre||[]).map(o=>asRecord(o,'squadre'))])}
function pathParts(r){return c(r.sourcePath).split('/')}
function root(r){return c(r.rootCollection||pathParts(r)[0])}
function sourceCommessaId(r,o={}){const p=pathParts(r),i=p.indexOf('commesse');if(i>=0&&p[i+1])return p[i+1];return c(first(o,['commessaId','idCommessa','commessa_id','jobId','commessaDocId','idCommessaPadre']))}
function jobFor(r,o={}){const cid=sourceCommessaId(r,o);if(cid){const byPath=(db.jobs||[]).find(j=>c(j.vcSourceId)===`commesse/${cid}`||c(j.sourceId)===cid||c(j.id)===cid);if(byPath)return byPath}const code=c(first(o,['codiceCommessa','commessaCode','codice','codCommessa']));const name=c(first(o,['commessaNome','nomeCommessa','commessa','cliente','descrizioneCommessa']));return(db.jobs||[]).find(j=>(code&&c(j.code)===code)||(name&&n(j.title)===n(name))||(name&&n(name).includes(n(j.title)))||(j.title&&n(j.title).includes(n(name))))||null}
function dateVal(o){const raw=first(o,['data','date','giorno','dataLavoro','workDate','dataOre','giornoLavoro','createdAt','timestamp','updatedAt']);if(raw&&typeof raw==='object'){if(raw.seconds)return new Date(raw.seconds*1000);if(raw._seconds)return new Date(raw._seconds*1000)}const d=new Date(raw||'');return isNaN(d)?null:d}
function isoDate(o){const d=dateVal(o);return d?d.toISOString().slice(0,10):c(first(o,['data','giorno','dataLavoro','giornoLavoro']))}
function displayDate(v){if(!v)return'';const d=new Date(v+'T12:00:00');return isNaN(d)?v:d.toLocaleDateString('it-IT')}
function memberText(v){if(Array.isArray(v))return v.map(x=>typeof x==='string'?x:(x?.nome||x?.name||x?.displayName||x?.operatoreNome||x?.email||x?.label||'')).filter(Boolean).join(', ');if(v&&typeof v==='object')return Object.values(v).map(x=>typeof x==='string'?x:(x?.nome||x?.name||x?.displayName||x?.email||x?.label||'')).filter(Boolean).join(', ');return c(v)}
function calcHours(o){let ore=num(first(o,['ore','oreLavorate','hours','totaleOre','durataOre','oreTotali','totalHours','oreGiornaliere']));if(ore)return ore;const start=c(first(o,['oraInizio','inizio','startTime','dalle'])),end=c(first(o,['oraFine','fine','endTime','alle'])),pause=num(first(o,['pausa','pausaOre','breakHours','orePausa']));if(/^\d{1,2}:\d{2}$/.test(start)&&/^\d{1,2}:\d{2}$/.test(end)){const [sh,sm]=start.split(':').map(Number),[eh,em]=end.split(':').map(Number);return Math.max(0,((eh*60+em)-(sh*60+sm))/60-pause)}return 0}
function hoursRecords(){return hoursSources().filter(r=>{const rt=n(root(r)),p=n(r.sourcePath);return /ore|hour|timbr/.test(rt)||/ore|hour|timbr/.test(p)}).map(r=>{const o=r.data||{},job=jobFor(r,o);return{path:r.sourcePath,jobId:job?.id||'',commessa:job?.title||c(first(o,['commessaNome','nomeCommessa','commessa','descrizioneCommessa']))||'Non associata',codice:job?.code||c(first(o,['codiceCommessa','commessaCode','codice','codCommessa'])),data:isoDate(o),operatore:c(first(o,['operatoreNome','operatore','nomeOperatore','nome','userName','displayName','dipendente','persona','utenteNome'])),squadra:c(first(o,['squadraNome','squadra','teamName','team','nomeSquadra'])),attivita:c(first(o,['attivita','attività','lavorazione','descrizione','note','causale','motivo'])),ore:calcHours(o),stato:c(first(o,['stato','status','approvalStatus','esito'])),raw:o}}).filter(x=>x.ore||x.data||x.operatore||x.commessa!=='Non associata')}
function squadRecords(){return squadSources().filter(r=>{const rt=n(root(r)),p=n(r.sourcePath);return /squad|team/.test(rt)||/squad|team/.test(p)}).map(r=>{const o=r.data||{},job=jobFor(r,o),members=first(o,['membri','componenti','operatori','utenti','personale','members','users','componentiSquadra','operatoriSquadra','assegnati']);return{path:r.sourcePath,jobId:job?.id||'',commessa:job?.title||c(first(o,['commessaNome','nomeCommessa','commessa','descrizioneCommessa']))||'Non associata',codice:job?.code||c(first(o,['codiceCommessa','commessaCode','codice','codCommessa'])),data:isoDate(o),squadra:c(first(o,['nomeSquadra','squadraNome','nome','squadra','teamName','team']))||'Squadra',responsabile:c(first(o,['responsabile','caposquadra','responsabileNome','leader','coordinatore','capoSquadra'])),componenti:memberText(members)||c(first(o,['componentiTesto','operatoriNomi','membriNomi','nomiOperatori'])),mezzo:c(first(o,['mezzo','mezzoNome','veicolo','targa'])),note:c(first(o,['note','nota','descrizione'])),stato:c(first(o,['stato','status'])),raw:o}}).filter(x=>x.data||x.componenti||x.responsabile||x.commessa!=='Non associata')}
function jobOptions(){return'<option value="">Tutte le commesse</option>'+(db.jobs||[]).slice().sort((a,b)=>c(a.title).localeCompare(c(b.title),'it')).map(j=>`<option value="${e(j.id)}">${e(j.title)}${j.code?' — '+e(j.code):''}</option>`).join('')}
function rowMatchesJob(x,jobId){if(!jobId)return true;if(x.jobId===jobId)return true;const j=(db.jobs||[]).find(z=>z.id===jobId);if(!j)return false;return (!!j.code&&c(x.codice)===c(j.code))||n(x.commessa)===n(j.title)||n(x.commessa).includes(n(j.title))}
function installNavAndViews(){const side=document.querySelector('.sidebar'),main=document.querySelector('.main');if(!side||!main)return;if(!document.querySelector('.nav[data-view="oreCommessa"]')){const anchor=document.querySelector('.nav[data-view="consuntivi"]');const b=document.createElement('button');b.className='nav';b.dataset.view='oreCommessa';b.textContent='Ore lavorate';b.onclick=()=>{nav('oreCommessa');drawHours()};anchor?.insertAdjacentElement('afterend',b)}if(!document.querySelector('.nav[data-view="storicoSquadre"]')){const anchor=document.querySelector('.nav[data-view="oreCommessa"]');const b=document.createElement('button');b.className='nav';b.dataset.view='storicoSquadre';b.textContent='Storico squadre';b.onclick=()=>{nav('storicoSquadre');drawSquads()};anchor?.insertAdjacentElement('afterend',b)}if(!document.getElementById('oreCommessa')){const s=document.createElement('section');s.id='oreCommessa';s.className='view';s.innerHTML=`<h1>Ore lavorate per commessa</h1><p class="subtitle">Dati già sincronizzati da Varga Cantieri, senza nuove letture Firestore.</p><div class="cards"><div class="card"><span>Righe ore</span><strong id="hoursRowsCount">0</strong></div><div class="card"><span>Totale ore</span><strong id="hoursTotal">0 h</strong></div><div class="card"><span>Operatori</span><strong id="hoursPeople">0</strong></div></div><div class="panel inline"><select id="hoursJob"></select><input id="hoursMonth" type="month"><input id="hoursSearch" placeholder="Cerca operatore, squadra, attività..."><button id="hoursExport" class="ghost">ESPORTA CSV</button></div><div class="panel"><div class="table-wrap"><table><thead><tr><th>Data</th><th>Commessa</th><th>Codice</th><th>Operatore</th><th>Squadra</th><th>Attività / Note</th><th>Ore</th><th>Stato</th></tr></thead><tbody id="hoursBody"></tbody></table></div></div>`;main.appendChild(s);s.querySelector('#hoursJob').innerHTML=jobOptions();['hoursJob','hoursMonth'].forEach(id=>s.querySelector('#'+id).onchange=drawHours);s.querySelector('#hoursSearch').oninput=drawHours;s.querySelector('#hoursExport').onclick=exportHours}
if(!document.getElementById('storicoSquadre')){const s=document.createElement('section');s.id='storicoSquadre';s.className='view';s.innerHTML=`<h1>Storico composizione squadre</h1><p class="subtitle">Composizione per commessa e giornata ricavata dai dati sincronizzati.</p><div class="cards"><div class="card"><span>Registrazioni</span><strong id="squadRowsCount">0</strong></div><div class="card"><span>Squadre</span><strong id="squadTeamsCount">0</strong></div><div class="card"><span>Giorni</span><strong id="squadDaysCount">0</strong></div></div><div class="panel inline"><select id="squadJob"></select><input id="squadMonth" type="month"><input id="squadSearch" placeholder="Cerca squadra, componente, responsabile..."><button id="squadExport" class="ghost">ESPORTA CSV</button></div><div class="panel"><div class="table-wrap"><table><thead><tr><th>Data</th><th>Commessa</th><th>Codice</th><th>Squadra</th><th>Responsabile</th><th>Componenti</th><th>Mezzo</th><th>Note</th></tr></thead><tbody id="squadBody"></tbody></table></div></div>`;main.appendChild(s);s.querySelector('#squadJob').innerHTML=jobOptions();['squadJob','squadMonth'].forEach(id=>s.querySelector('#'+id).onchange=drawSquads);s.querySelector('#squadSearch').oninput=drawSquads;s.querySelector('#squadExport').onclick=exportSquads}}
function selectedHours(){let rows=hoursRecords(),job=c(document.getElementById('hoursJob')?.value),month=c(document.getElementById('hoursMonth')?.value),q=n(document.getElementById('hoursSearch')?.value);return rows.filter(x=>rowMatchesJob(x,job)&&(!month||c(x.data).startsWith(month))&&(!q||n([x.commessa,x.codice,x.operatore,x.squadra,x.attivita,x.stato].join(' ')).includes(q))).sort((a,b)=>c(b.data).localeCompare(c(a.data)))}
function selectedSquads(){let rows=squadRecords(),job=c(document.getElementById('squadJob')?.value),month=c(document.getElementById('squadMonth')?.value),q=n(document.getElementById('squadSearch')?.value);return rows.filter(x=>rowMatchesJob(x,job)&&(!month||c(x.data).startsWith(month))&&(!q||n([x.commessa,x.codice,x.squadra,x.responsabile,x.componenti,x.mezzo,x.note].join(' ')).includes(q))).sort((a,b)=>c(b.data).localeCompare(c(a.data)))}
function drawHours(){const body=document.getElementById('hoursBody');if(!body)return;const rows=selectedHours(),total=rows.reduce((s,x)=>s+x.ore,0);document.getElementById('hoursRowsCount').textContent=rows.length;document.getElementById('hoursTotal').textContent=(Math.round(total*100)/100).toLocaleString('it-IT')+' h';document.getElementById('hoursPeople').textContent=new Set(rows.map(x=>n(x.operatore)).filter(Boolean)).size;body.innerHTML=rows.length?rows.map(x=>`<tr><td>${e(displayDate(x.data))}</td><td><b>${e(x.commessa)}</b></td><td>${e(x.codice)}</td><td>${e(x.operatore)}</td><td>${e(x.squadra)}</td><td>${e(x.attivita)}</td><td style="text-align:right"><b>${e((Math.round(x.ore*100)/100).toLocaleString('it-IT'))}</b></td><td>${e(x.stato)}</td></tr>`).join(''):'<tr><td colspan="8" class="empty">Nessuna ora trovata. Premi SINCRONIZZA TUTTO e riprova senza filtro mese.</td></tr>'}
function drawSquads(){const body=document.getElementById('squadBody');if(!body)return;const rows=selectedSquads();document.getElementById('squadRowsCount').textContent=rows.length;document.getElementById('squadTeamsCount').textContent=new Set(rows.map(x=>n(x.squadra)).filter(Boolean)).size;document.getElementById('squadDaysCount').textContent=new Set(rows.map(x=>x.data).filter(Boolean)).size;body.innerHTML=rows.length?rows.map(x=>`<tr><td>${e(displayDate(x.data))}</td><td><b>${e(x.commessa)}</b></td><td>${e(x.codice)}</td><td>${e(x.squadra)}</td><td>${e(x.responsabile)}</td><td>${e(x.componenti)}</td><td>${e(x.mezzo)}</td><td>${e(x.note)}</td></tr>`).join(''):'<tr><td colspan="8" class="empty">Nessuna squadra trovata. Premi SINCRONIZZA TUTTO e riprova senza filtro mese.</td></tr>'}
function download(name,heads,rows){const csv='\ufeff'+[heads,...rows].map(r=>r.map(v=>'"'+String(v??'').replace(/"/g,'""')+'"').join(';')).join('\n'),a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.download=name;a.click();URL.revokeObjectURL(a.href)}
function exportHours(){const rows=selectedHours();download(`Ore-lavorate-${new Date().toISOString().slice(0,10)}.csv`,['Data','Commessa','Codice','Operatore','Squadra','Attività / Note','Ore','Stato'],rows.map(x=>[x.data,x.commessa,x.codice,x.operatore,x.squadra,x.attivita,x.ore,x.stato]))}
function exportSquads(){const rows=selectedSquads();download(`Storico-squadre-${new Date().toISOString().slice(0,10)}.csv`,['Data','Commessa','Codice','Squadra','Responsabile','Componenti','Mezzo','Note'],rows.map(x=>[x.data,x.commessa,x.codice,x.squadra,x.responsabile,x.componenti,x.mezzo,x.note]))}
function refreshOptions(){['hoursJob','squadJob'].forEach(id=>{const el=document.getElementById(id);if(!el)return;const old=el.value;el.innerHTML=jobOptions();if([...el.options].some(o=>o.value===old))el.value=old})}
const obs=new MutationObserver(installNavAndViews);obs.observe(document.documentElement,{childList:true,subtree:true});if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>{installNavAndViews();drawHours();drawSquads()});else{installNavAndViews();drawHours();drawSquads()}setInterval(()=>{refreshOptions();if(document.getElementById('oreCommessa')?.classList.contains('active-view'))drawHours();if(document.getElementById('storicoSquadre')?.classList.contains('active-view'))drawSquads()},2500);
})();