/* Ore lavorate + storico squadre: espansione struttura reale Varga Cantieri. */
(function(){
'use strict';
const c=v=>String(v??'').trim();
const n=v=>c(v).toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'');
const e=v=>String(v??'').replace(/[&<>"']/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[x]));
const num=v=>{if(typeof v==='number')return Number.isFinite(v)?v:0;let s=c(v).replace(/\s/g,'');if(!s)return 0;if(s.includes(',')&&s.includes('.'))s=s.lastIndexOf(',')>s.lastIndexOf('.')?s.replace(/\./g,'').replace(',','.'):s.replace(/,/g,'');else s=s.replace(',','.');return Number(s.replace(/[^0-9.-]/g,''))||0};
const first=(o,names)=>{for(const wanted of names){const k=Object.keys(o||{}).find(x=>n(x)===n(wanted));if(k!=null&&o[k]!=null&&(!(typeof o[k]==='string')||c(o[k])!==''))return o[k]}return''};
const merge=(...objs)=>Object.assign({},...objs.filter(x=>x&&typeof x==='object'&&!Array.isArray(x)));
const asRecord=(o,kind)=>({sourcePath:c(o?.vcSourceId||o?.sourcePath||`${kind}/${o?.id||''}`),rootCollection:c(o?.vcRootCollection||o?.rootCollection||kind),data:o?.data&&typeof o.data==='object'?o.data:o});
function uniqueRecords(arr){const m=new Map();arr.forEach((r,i)=>{if(!r)return;const k=c(r.sourcePath)||`${r.rootCollection||''}:${r.id||''}:${i}`;if(!m.has(k))m.set(k,r)});return[...m.values()]}
function hoursSources(){return uniqueRecords([...(db.vcRecords||[]),...(db.vcOre||[]).map(o=>asRecord(o,'oreReports'))]).filter(r=>/ore|hour|timbr/i.test(c(r.rootCollection)+' '+c(r.sourcePath)))}
function squadSources(){return uniqueRecords([...(db.vcRecords||[]),...(db.vcSquadre||[]).map(o=>asRecord(o,'squadreStorico'))]).filter(r=>/squadr|team/i.test(c(r.rootCollection)+' '+c(r.sourcePath)))}
function pathParts(r){return c(r?.sourcePath).split('/')}
function sourceCommessaId(r,o={}){const p=pathParts(r),i=p.indexOf('commesse');if(i>=0&&p[i+1])return p[i+1];return c(first(o,['commessaId','idCommessa','commessa_id','jobId','commessaDocId','idCommessaPadre']))}
function jobFor(r,...layers){const o=merge(...layers);const cid=sourceCommessaId(r,o);if(cid){const byId=(db.jobs||[]).find(j=>c(j.vcSourceId)===`commesse/${cid}`||c(j.sourceId)===cid||c(j.id)===cid);if(byId)return byId}const code=c(first(o,['codiceCommessa','commessaCode','codice','codCommessa']));const name=c(first(o,['commessaNome','nomeCommessa','commessa','cliente','descrizioneCommessa']));return(db.jobs||[]).find(j=>(code&&c(j.code)===code)||(name&&n(j.title)===n(name))||(name&&n(name).includes(n(j.title)))||(name&&n(j.title).includes(n(name))))||null}
function rawDate(...layers){for(const o of layers){const v=first(o||{},['date','data','giorno','dataLavoro','workDate','dataOre','giornoLavoro','riferimentoData','dateKey','createdAt','timestamp']);if(v!==''&&v!=null)return v}return''}
function isoDateFrom(...layers){let raw=rawDate(...layers);if(raw&&typeof raw==='object'){if(typeof raw.toDate==='function')raw=raw.toDate();else if(raw.seconds!=null)raw=new Date(raw.seconds*1000);else if(raw._seconds!=null)raw=new Date(raw._seconds*1000)}if(raw instanceof Date)return isNaN(raw)?'':`${raw.getFullYear()}-${String(raw.getMonth()+1).padStart(2,'0')}-${String(raw.getDate()).padStart(2,'0')}`;let s=c(raw);let m=s.match(/^(\d{4})-(\d{2})-(\d{2})/);if(m)return`${m[1]}-${m[2]}-${m[3]}`;m=s.match(/^(\d{1,2})[/.\-](\d{1,2})[/.\-](\d{4})/);if(m)return`${m[3]}-${m[2].padStart(2,'0')}-${m[1].padStart(2,'0')}`;const d=new Date(s);return isNaN(d)?s:d.toISOString().slice(0,10)}
function displayDate(v){if(!v)return'';const d=new Date(v+'T12:00:00');return isNaN(d)?v:d.toLocaleDateString('it-IT')}
function splitValues(v){if(Array.isArray(v))return v.flatMap(splitValues).filter(Boolean);if(v&&typeof v==='object'){const name=c(v.nomeCompleto||v.displayName||v.nomeOperatore||v.operatore||v.name||`${v.nome||''} ${v.cognome||''}`);if(name)return[name];return Object.values(v).flatMap(splitValues).filter(Boolean)}return c(v).split(/[,;|\n]+/).map(c).filter(Boolean)}
function uniqueText(values){const seen=new Set();return values.filter(v=>{const k=n(v);if(!k||seen.has(k))return false;seen.add(k);return true})}
function memberText(v){return uniqueText(splitValues(v)).join(', ')}
function calcHours(o){for(const key of ['ore','hours','totaleOre','oreTotali','quantita','oreLavorate','durataOre','totalHours']){const v=first(o,[key]);const h=num(v);if(h>0)return h}const start=c(first(o,['oraInizio','inizio','startTime','dalle'])),end=c(first(o,['oraFine','fine','endTime','alle'])),pause=num(first(o,['pausa','pausaOre','breakHours','orePausa']));if(/^\d{1,2}:\d{2}$/.test(start)&&/^\d{1,2}:\d{2}$/.test(end)){const [sh,sm]=start.split(':').map(Number),[eh,em]=end.split(':').map(Number);let mins=(eh*60+em)-(sh*60+sm);if(mins<0)mins+=1440;return Math.max(0,mins/60-pause)}return 0}
function operatorName(row,entry,report){const o=merge(report,entry,row);let name=c(first(o,['operatore','nomeOperatore','operatoreNome','nomeCompleto','displayName','name','dipendente','persona','utenteNome']));if(!name){const nome=c(first(o,['nome'])),cognome=c(first(o,['cognome']));name=c(`${nome} ${cognome}`)}return name}
function expandHourReport(r){const report=r.data||{};const entries=Array.isArray(report.entries)&&report.entries.length?report.entries:[report];const out=[];entries.forEach((entry,ei)=>{const rows=Array.isArray(entry?.rows)&&entry.rows.length?entry.rows:(Array.isArray(entry?.operatori)&&entry.operatori.length?entry.operatori:[entry]);rows.forEach((row,ri)=>{if(!row||typeof row!=='object')return;const combined=merge(report,entry,row),job=jobFor(r,report,entry,row),ore=calcHours(row)||calcHours(entry);const commessa=job?.title||c(first(combined,['commessaNome','nomeCommessa','commessa','descrizioneCommessa']))||'Non associata';const codice=job?.code||c(first(combined,['codiceCommessa','commessaCode','codice','codCommessa']));const operatore=operatorName(row,entry,report);const squadra=c(first(combined,['squadraNome','nomeSquadra','squadra','teamName','team']));const attivita=c(first(combined,['attivita','attività','lavorazione','descrizione','note','causale','motivo']));const stato=c(first(combined,['stato','status','approvalStatus','esito']));const data=isoDateFrom(row,entry,report);if(ore>0||operatore||data)out.push({key:`${r.sourcePath}:${ei}:${ri}`,jobId:job?.id||'',commessa,codice,data,operatore,squadra,attivita,ore,stato})})});return out}
function hoursRecords(){const all=hoursSources().flatMap(expandHourReport),m=new Map();all.forEach(x=>{const k=[x.key,x.data,x.commessa,x.operatore,x.ore].join('|');if(!m.has(k))m.set(k,x)});return[...m.values()]}
function expandSquadComposition(r){const composition=r.data||{};const rows=Array.isArray(composition.squadre)&&composition.squadre.length?composition.squadre:(Array.isArray(composition.rows)&&composition.rows.length?composition.rows:[composition]);const out=[];rows.forEach((row,i)=>{if(!row||typeof row!=='object')return;const combined=merge(composition,row),job=jobFor(r,composition,row);const personnel=first(row,['personale','operatori','componenti','membri','utenti','members','users']);const capo=c(first(row,['caposquadra','capoSquadra','responsabile','responsabileNome','leader','coordinatore']));let persone=memberText(personnel);if(capo){const list=uniqueText([capo,...splitValues(personnel)]);persone=list.join(', ')}const mezzi=memberText(first(row,['mezzi','veicoli','attrezzature','mezzo','veicolo']));const nomeSquadra=c(first(row,['nomeSquadra','squadraNome','nome','squadra','teamName']))||`Squadra ${i+1}`;const data=isoDateFrom(row,composition);const commessa=job?.title||c(first(combined,['commessaNome','nomeCommessa','commessa','descrizioneCommessa']))||'Non associata';const codice=job?.code||c(first(combined,['codiceCommessa','commessaCode','codice','codCommessa']));const note=c(first(row,['note','nota','descrizione']));if(data||persone||capo||mezzi)out.push({key:`${r.sourcePath}:${i}`,jobId:job?.id||'',commessa,codice,data,squadra:nomeSquadra,responsabile:capo,componenti:persone,mezzo:mezzi,note})});return out}
function squadRecords(){const all=squadSources().flatMap(expandSquadComposition),m=new Map();all.forEach(x=>{const k=[x.key,x.data,x.commessa,x.squadra,x.componenti].join('|');if(!m.has(k))m.set(k,x)});return[...m.values()]}
function jobOptions(){return'<option value="">Tutte le commesse</option>'+(db.jobs||[]).slice().sort((a,b)=>c(a.title).localeCompare(c(b.title),'it')).map(j=>`<option value="${e(j.id)}">${e(j.title)}${j.code?' — '+e(j.code):''}</option>`).join('')}
function rowMatchesJob(x,jobId){if(!jobId)return true;if(x.jobId===jobId)return true;const j=(db.jobs||[]).find(z=>z.id===jobId);if(!j)return false;return(!!j.code&&c(x.codice)===c(j.code))||n(x.commessa)===n(j.title)||(n(x.commessa)&&n(x.commessa).includes(n(j.title)))}
function installNavAndViews(){const side=document.querySelector('.sidebar'),main=document.querySelector('.main');if(!side||!main)return;if(!document.querySelector('.nav[data-view="oreCommessa"]')){const anchor=document.querySelector('.nav[data-view="consuntivi"]');const b=document.createElement('button');b.className='nav';b.dataset.view='oreCommessa';b.textContent='Ore lavorate';b.onclick=()=>{nav('oreCommessa');drawHours()};anchor?.insertAdjacentElement('afterend',b)}if(!document.querySelector('.nav[data-view="storicoSquadre"]')){const anchor=document.querySelector('.nav[data-view="oreCommessa"]');const b=document.createElement('button');b.className='nav';b.dataset.view='storicoSquadre';b.textContent='Storico squadre';b.onclick=()=>{nav('storicoSquadre');drawSquads()};anchor?.insertAdjacentElement('afterend',b)}
if(!document.getElementById('oreCommessa')){const s=document.createElement('section');s.id='oreCommessa';s.className='view';s.innerHTML=`<h1>Ore lavorate per commessa</h1><p class="subtitle">Righe operatori estratte dai report ore sincronizzati da Varga Cantieri.</p><div class="cards"><div class="card"><span>Righe ore</span><strong id="hoursRowsCount">0</strong></div><div class="card"><span>Totale ore</span><strong id="hoursTotal">0 h</strong></div><div class="card"><span>Operatori</span><strong id="hoursPeople">0</strong></div></div><div class="panel inline"><select id="hoursJob"></select><input id="hoursMonth" type="month"><input id="hoursSearch" placeholder="Cerca operatore, squadra, attività..."><button id="hoursExport" class="ghost">ESPORTA CSV</button></div><div class="panel"><p id="hoursDiag" class="muted"></p><div class="table-wrap"><table><thead><tr><th>Data</th><th>Commessa</th><th>Codice</th><th>Operatore</th><th>Squadra</th><th>Attività / Note</th><th>Ore</th><th>Stato</th></tr></thead><tbody id="hoursBody"></tbody></table></div></div>`;main.appendChild(s);s.querySelector('#hoursJob').innerHTML=jobOptions();['hoursJob','hoursMonth'].forEach(id=>s.querySelector('#'+id).onchange=drawHours);s.querySelector('#hoursSearch').oninput=drawHours;s.querySelector('#hoursExport').onclick=exportHours}
if(!document.getElementById('storicoSquadre')){const s=document.createElement('section');s.id='storicoSquadre';s.className='view';s.innerHTML=`<h1>Storico composizione squadre</h1><p class="subtitle">Composizione reale delle squadre per commessa e giornata.</p><div class="cards"><div class="card"><span>Registrazioni</span><strong id="squadRowsCount">0</strong></div><div class="card"><span>Squadre</span><strong id="squadTeamsCount">0</strong></div><div class="card"><span>Giorni</span><strong id="squadDaysCount">0</strong></div></div><div class="panel inline"><select id="squadJob"></select><input id="squadMonth" type="month"><input id="squadSearch" placeholder="Cerca squadra, componente, responsabile..."><button id="squadExport" class="ghost">ESPORTA CSV</button></div><div class="panel"><p id="squadDiag" class="muted"></p><div class="table-wrap"><table><thead><tr><th>Data</th><th>Commessa</th><th>Codice</th><th>Squadra</th><th>Caposquadra</th><th>Componenti</th><th>Mezzi</th><th>Note</th></tr></thead><tbody id="squadBody"></tbody></table></div></div>`;main.appendChild(s);s.querySelector('#squadJob').innerHTML=jobOptions();['squadJob','squadMonth'].forEach(id=>s.querySelector('#'+id).onchange=drawSquads);s.querySelector('#squadSearch').oninput=drawSquads;s.querySelector('#squadExport').onclick=exportSquads}}
function selectedHours(){let rows=hoursRecords(),job=c(document.getElementById('hoursJob')?.value),month=c(document.getElementById('hoursMonth')?.value),q=n(document.getElementById('hoursSearch')?.value);return rows.filter(x=>rowMatchesJob(x,job)&&(!month||c(x.data).startsWith(month))&&(!q||n([x.commessa,x.codice,x.operatore,x.squadra,x.attivita,x.stato].join(' ')).includes(q))).sort((a,b)=>c(b.data).localeCompare(c(a.data)))}
function selectedSquads(){let rows=squadRecords(),job=c(document.getElementById('squadJob')?.value),month=c(document.getElementById('squadMonth')?.value),q=n(document.getElementById('squadSearch')?.value);return rows.filter(x=>rowMatchesJob(x,job)&&(!month||c(x.data).startsWith(month))&&(!q||n([x.commessa,x.codice,x.squadra,x.responsabile,x.componenti,x.mezzo,x.note].join(' ')).includes(q))).sort((a,b)=>c(b.data).localeCompare(c(a.data)))}
function drawHours(){const body=document.getElementById('hoursBody');if(!body)return;const all=hoursRecords(),rows=selectedHours(),total=rows.reduce((s,x)=>s+x.ore,0);document.getElementById('hoursRowsCount').textContent=rows.length;document.getElementById('hoursTotal').textContent=(Math.round(total*100)/100).toLocaleString('it-IT')+' h';document.getElementById('hoursPeople').textContent=new Set(rows.map(x=>n(x.operatore)).filter(Boolean)).size;const diag=document.getElementById('hoursDiag');if(diag)diag.textContent=`Sorgenti sincronizzate: ${hoursSources().length} report • Righe operatori estratte: ${all.length}`;body.innerHTML=rows.length?rows.map(x=>`<tr><td>${e(displayDate(x.data))}</td><td><b>${e(x.commessa)}</b></td><td>${e(x.codice)}</td><td>${e(x.operatore)}</td><td>${e(x.squadra)}</td><td>${e(x.attivita)}</td><td style="text-align:right"><b>${e((Math.round(x.ore*100)/100).toLocaleString('it-IT'))}</b></td><td>${e(x.stato)}</td></tr>`).join(''):'<tr><td colspan="8" class="empty">Nessuna ora per i filtri selezionati. Togli il filtro mese oppure premi SINCRONIZZA TUTTO.</td></tr>'}
function drawSquads(){const body=document.getElementById('squadBody');if(!body)return;const all=squadRecords(),rows=selectedSquads();document.getElementById('squadRowsCount').textContent=rows.length;document.getElementById('squadTeamsCount').textContent=new Set(rows.map(x=>[x.data,n(x.commessa),n(x.squadra)].join('|'))).size;document.getElementById('squadDaysCount').textContent=new Set(rows.map(x=>x.data).filter(Boolean)).size;const diag=document.getElementById('squadDiag');if(diag)diag.textContent=`Sorgenti sincronizzate: ${squadSources().length} composizioni • Righe squadra estratte: ${all.length}`;body.innerHTML=rows.length?rows.map(x=>`<tr><td>${e(displayDate(x.data))}</td><td><b>${e(x.commessa)}</b></td><td>${e(x.codice)}</td><td>${e(x.squadra)}</td><td>${e(x.responsabile)}</td><td>${e(x.componenti)}</td><td>${e(x.mezzo)}</td><td>${e(x.note)}</td></tr>`).join(''):'<tr><td colspan="8" class="empty">Nessuna composizione per i filtri selezionati. Togli il filtro mese oppure premi SINCRONIZZA TUTTO.</td></tr>'}
function download(name,heads,rows){const csv='\ufeff'+[heads,...rows].map(r=>r.map(v=>'"'+String(v??'').replace(/"/g,'""')+'"').join(';')).join('\n'),a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.download=name;a.click();URL.revokeObjectURL(a.href)}
function exportHours(){const rows=selectedHours();download(`Ore-lavorate-${new Date().toISOString().slice(0,10)}.csv`,['Data','Commessa','Codice','Operatore','Squadra','Attività / Note','Ore','Stato'],rows.map(x=>[x.data,x.commessa,x.codice,x.operatore,x.squadra,x.attivita,x.ore,x.stato]))}
function exportSquads(){const rows=selectedSquads();download(`Storico-squadre-${new Date().toISOString().slice(0,10)}.csv`,['Data','Commessa','Codice','Squadra','Caposquadra','Componenti','Mezzi','Note'],rows.map(x=>[x.data,x.commessa,x.codice,x.squadra,x.responsabile,x.componenti,x.mezzo,x.note]))}
function refreshOptions(){['hoursJob','squadJob'].forEach(id=>{const el=document.getElementById(id);if(!el)return;const old=el.value;el.innerHTML=jobOptions();if([...el.options].some(o=>o.value===old))el.value=old})}
const obs=new MutationObserver(()=>installNavAndViews());obs.observe(document.documentElement,{childList:true,subtree:true});if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>{installNavAndViews();drawHours();drawSquads()});else{installNavAndViews();drawHours();drawSquads()}setInterval(()=>{refreshOptions();if(document.getElementById('oreCommessa')?.classList.contains('active-view'))drawHours();if(document.getElementById('storicoSquadre')?.classList.contains('active-view'))drawSquads()},2500);
window.VargaWorkforceHours=hoursRecords;
})();
