'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const L=process.env.QUOTE_PDF_LIB?require(process.env.QUOTE_PDF_LIB):require('pdf-lib');
const api=require('../preventivi-pdf-layout.js');const dir=path.join(__dirname,'../build/quote-output');fs.mkdirSync(dir,{recursive:true});
const sidebarBytes=fs.readFileSync(path.join(__dirname,'../assets/avola-preventivo-sidebar.png'));
const base={number:'TEST-01',date:'09/09/2026',place:'Località prova',client:{name:'CLIENTE DI PROVA',address:'Via Esempio 1',cap:'00000',city:'Comune'},subject:'Intervento dimostrativo',intro:'Test del modello senza dati aziendali.',rows:[{code:'PROVA.1',description:'Descrizione di prova con accenti, unità e simboli m² e m³.',unit:'h',qty:24,price:32.076}],subtotal:769.82,referenceText:'Riferimento economico: prezzario di prova.'};
let checks=0;function ok(name,fn){fn();checks++;console.log('PASS',name)}
(async()=>{
const g=await api.generate(base,{PDFLib:L,sidebarBytes,flatten:true});const e=await api.generate(base,{PDFLib:L,sidebarBytes,flatten:false});
fs.writeFileSync(path.join(dir,'normal.pdf'),g.bytes);fs.writeFileSync(path.join(dir,'editable.pdf'),e.bytes);fs.writeFileSync(path.join(dir,'layout.json'),JSON.stringify(g.layout,null,2));
const nd=await L.PDFDocument.load(g.bytes),ed=await L.PDFDocument.load(e.bytes),fields=ed.getForm().getFields(),texts=g.layout.pages.flatMap(p=>p.text);
ok('A4 misurato',()=>{assert.equal(nd.getPageCount(),1);assert.equal(nd.getPage(0).getWidth(),595.2756)});
ok('Cinque colonne senza U.M. separata',()=>{assert.equal(api.geometry.columns.length,6);assert(!texts.some(t=>t.text==='U.M.'))});
ok('Data e luogo su una riga',()=>{const t=texts.find(t=>t.text==='Località prova, il 09/09/2026');assert.equal(t.x,147.42);assert.equal(t.y,79.32)});
ok('Destinatario a destra',()=>{const t=texts.find(t=>t.text==='CLIENTE DI PROVA');assert.equal(t.x,374.16);assert.equal(t.y,106.91999999999999)});
ok('Titolo compatto',()=>{const t=texts.find(t=>t.text==='OFFERTA TEST-01 del 09/09/2026');assert.equal(t.x,147.42);assert.equal(t.y,147.42)});
ok('Oggetto con partenza del modello',()=>assert.equal(texts.find(t=>t.text==='OGGETTO:').y,182.58));
ok('Tabella alla quota del modello',()=>assert.equal(g.layout.rows[0].top,298.74));
ok('Tre decimali nel prezzo',()=>assert.equal(api.unitPrice(base.rows[0]),'€ 32,076/h'));
ok('Unità nella quantità',()=>assert.equal(api.quantity(base.rows[0]),'24 h'));
ok('Separatore migliaia italiano',()=>assert.equal(api.amount(3945.34),'€ 3.945,34'));
ok('Importi a due decimali',()=>assert.equal(api.amount(32.076*24),'€ 769,82'));
ok('Totale a sinistra su due righe',()=>{const t=texts.find(t=>t.text==='TOTALE OFFERTA (IVA ESCLUSA)');const a=texts.find(t=>t.text==='€ 769,82'&&t.size===11.52);assert.equal(t.x,147.42);assert.equal(a.x,147.42);assert(Math.abs(a.y-t.y-14.94)<.0001)});
ok('Nota sicurezza presente',()=>assert(texts.some(t=>t.text==='(oneri della sicurezza inclusi)')));
ok('PDF normale senza widget',()=>assert.equal(nd.getForm().getFields().length,0));
ok('PDF compilabile con valori e appearance',()=>{assert(fields.length>5);for(const f of fields){assert(f.getText()!==undefined);for(const w of f.acroField.getWidgets()){assert(w.getAppearances().normal);assert.equal(w.getFlags()&4,4)}}});
ok('Nessun pulsante stampa nel documento',()=>assert(!fields.some(f=>f.getName().includes('stampa'))));
ok('Stessi testi e coordinate in normale e compilabile',()=>assert.deepEqual(g.layout.pages,e.layout.pages));
ok('Nessuna mutazione del preventivo',()=>assert.equal(base.rows[0].price,32.076));
let seal;await api.generate(base,{PDFLib:L,sidebarBytes,drawSeal:async(pdf,page,box)=>{seal=box}});
ok('Firma separata dal corpo e a destra',()=>{assert.equal(seal.x,377.76);assert.equal(seal.width,188.64);assert(seal.y>0)});
const long={...base,referenceText:('Riferimento prova con molti prezzari selezionati. ').repeat(7)};const lr=await api.generate(long,{PDFLib:L,sidebarBytes});
ok('Riferimento lungo va a capo senza uscire',()=>assert(lr.layout.pages.flatMap(p=>p.text).filter(t=>t.size===7.5).every(t=>t.x+t.width<=574.681)));
const many={...base,rows:Array.from({length:45},(_,i)=>({...base.rows[0],code:'TEST'+i}))};const mg=await api.generate(many,{PDFLib:L,sidebarBytes});fs.writeFileSync(path.join(dir,'multipage.pdf'),mg.bytes);
ok('Più pagine senza perdere righe',()=>{assert(mg.layout.pages.length>1);assert.equal(new Set(mg.layout.rows.map(r=>r.index)).size,45);assert(mg.layout.rows.every(r=>r.top+r.height<=742.001))});
ok('Testata ripetuta per le righe sulle pagine successive',()=>{for(const page of new Set(mg.layout.rows.map(r=>r.page)))assert(mg.layout.pages[page-1].text.some(t=>t.text==='Descrizione'))});
const huge={...base,rows:[{...base.rows[0],description:('Testo lungo da continuare senza tagliare. ').repeat(300)}]};const hg=await api.generate(huge,{PDFLib:L,sidebarBytes});fs.writeFileSync(path.join(dir,'long-row.pdf'),hg.bytes);
ok('Riga molto lunga suddivisa senza testo perso',()=>{assert(hg.layout.rows.length>1);const actual=hg.layout.pages.flatMap(p=>p.text).filter(t=>t.x===205.68).map(t=>t.text).join(' ');assert.equal(actual.trim(),huge.rows[0].description.trim())});
let rejected=false;try{await api.generate({...base,rows:[{...base.rows[0],price:Infinity}]},{PDFLib:L,sidebarBytes})}catch(_){rejected=true}ok('Valori numerici invalidi bloccati',()=>assert(rejected));
rejected=false;try{await api.generate({...base,subject:'S'.repeat(20000)},{PDFLib:L,sidebarBytes})}catch(_){rejected=true}ok('Intestazione eccessiva segnalata, non troncata',()=>assert(rejected));
const nodata=await api.generate({...base,client:{name:'Cliente senza indirizzo'}},{PDFLib:L,sidebarBytes});ok('Nessun indirizzo inventato',()=>assert(!nodata.layout.pages[0].text.some(t=>t.text==='Via Esempio 1')));
fs.writeFileSync(path.join(dir,'results.json'),JSON.stringify({checks,passed:checks,scope:'pdf-lib real; synthetic quotes; no production business data'},null,2));console.log(checks+'/'+checks+' passed');
})().catch(error=>{console.error(error);process.exit(1)});
